import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {ACTIVITY_RELATIONSHIP_KINDS,activityRelationshipIssues,behaviorRelationshipLabel,reconnectActivityFlow,validateBehaviorConnection} from '../public/src/behavior-model.js';
import {DIAGRAMS} from '../public/src/sysml-profile.js';
import {ACTIVITY_FLOW_TYPES} from '../public/src/activity-manifest.js';
import {relationshipCapabilityFor} from '../public/src/sysml/conformance-registry.js';

const add=(p,kind,id,owner,extra={})=>{const e=Object.assign(defaultElement(kind,owner),{id,name:id},extra);p.elements.push(e);return e};
function fixture(){const p=createProject('Activity relationships'),root=p.root.id,activity=add(p,'Activity','activity',root),region=add(p,'InterruptibleActivityRegion','region','activity'),inside=add(p,'Action','inside','region'),outside=add(p,'Action','outside','activity'),final=add(p,'ActivityFinalNode','final','activity'),initial=add(p,'InitialNode','initial','activity'),typeA=add(p,'DataType','type-a',root),typeB=add(p,'DataType','type-b',root),sourceAction=add(p,'Action','source-action','activity'),targetAction=add(p,'Action','target-action','activity'),output=add(p,'OutputPin','output',sourceAction.id,{typeRef:typeA.id,carriedTypeId:typeA.id}),input=add(p,'InputPin','input',targetAction.id,{typeRef:typeA.id,carriedTypeId:typeA.id}),badInput=add(p,'InputPin','bad-input',targetAction.id,{typeRef:typeB.id,carriedTypeId:typeB.id});const d={id:'diagram',name:'Activity',diagramType:'Activity Diagram',ownerId:root,contextId:activity.id,nodes:[inside,outside,final,initial,sourceAction,targetAction,output,input,badInput,region].map((e,i)=>({id:`n-${e.id}`,elementId:e.id,x:60+i*70,y:100+(i%2)*150,width:e.kind.endsWith('Pin')?16:190,height:e.kind.endsWith('Pin')?16:110})),edges:[]};p.diagrams.push(d);p.activeDiagramId=d.id;return{p,d,activity,region,inside,outside,final,initial,typeA,typeB,sourceAction,targetAction,output,input,badInput};}

test('Activity Diagram exposes exactly the qualified production relationship surface',()=>{const expected=['ControlFlow','ObjectFlow','InterruptingEdge','Allocate'];assert.deepEqual(DIAGRAMS['Activity Diagram'].relationships,expected);assert.deepEqual(ACTIVITY_FLOW_TYPES,expected);assert.deepEqual(ACTIVITY_RELATIONSHIP_KINDS,['ControlFlow','ObjectFlow','InterruptingEdge']);for(const kind of expected){const capability=relationshipCapabilityFor('Activity Diagram',kind);assert.equal(capability.maturity,'working',kind);assert.equal(capability.testFixtureId,'activity-relationship-workflow',kind);assert.deepEqual(capability.knownLimitations,[],kind);}});

test('ControlFlow enforces Activity context and initial/final direction rules',()=>{const{p,initial,outside,final}=fixture();assert.equal(validateBehaviorConnection(p,'ControlFlow',initial.id,outside.id).valid,true);assert.equal(validateBehaviorConnection(p,'ControlFlow',outside.id,initial.id).valid,false);assert.equal(validateBehaviorConnection(p,'ControlFlow',final.id,outside.id).valid,false);assert.equal(validateBehaviorConnection(p,'ControlFlow',outside.id,outside.id).valid,false);const otherActivity=add(p,'Activity','other-activity',p.root.id),other=add(p,'Action','other',otherActivity.id);assert.equal(validateBehaviorConnection(p,'ControlFlow',outside.id,other.id).valid,false);});

test('ObjectFlow requires directed compatible typed object endpoints',()=>{const{p,output,input,badInput}=fixture();assert.equal(validateBehaviorConnection(p,'ObjectFlow',output.id,input.id).valid,true);assert.equal(validateBehaviorConnection(p,'ObjectFlow',input.id,output.id).valid,false);const invalid=validateBehaviorConnection(p,'ObjectFlow',output.id,badInput.id);assert.equal(invalid.valid,false);assert.match(invalid.message,/no common compatible classifier/);});

test('InterruptingEdge originates inside an interruptible region and exits that region',()=>{const{p,inside,outside,region}=fixture();assert.equal(validateBehaviorConnection(p,'InterruptingEdge',inside.id,outside.id).valid,true);const same=add(p,'Action','same',region.id);assert.equal(validateBehaviorConnection(p,'InterruptingEdge',inside.id,same.id).valid,false);assert.equal(validateBehaviorConnection(p,'InterruptingEdge',outside.id,inside.id).valid,false);});

test('Activity edge properties normalize, label, validate, reconnect and survive reload',()=>{const{p,d,inside,outside,output,input,typeA}=fixture();const control=defaultRelationship('ControlFlow',inside.id,outside.id,'activity');control.name='continue';control.guard='ready';control.weight='2';const object=defaultRelationship('ObjectFlow',output.id,input.id,'activity');object.guard='valid';object.weight='3';object.carriedTypeId=typeA.id;const interrupt=defaultRelationship('InterruptingEdge',inside.id,outside.id,'activity');interrupt.guard='abort';interrupt.weight='4';p.relationships.push(control,object,interrupt);assert.equal(behaviorRelationshipLabel(p,control),'continue [ready] {weight=2}');assert.equal(behaviorRelationshipLabel(p,object),'[valid] {weight=3} : type-a');assert.equal(behaviorRelationshipLabel(p,interrupt),'[abort] {weight=4}');for(const r of [control,object,interrupt])assert.deepEqual(activityRelationshipIssues(p,r),[]);const targetNode=d.nodes.find(n=>n.elementId===outside.id);assert.equal(reconnectActivityFlow(p,d,interrupt,'target',targetNode).semanticId,outside.id);const loaded=normalizeProject(JSON.parse(JSON.stringify(p)));for(const id of [control.id,object.id,interrupt.id]){const r=loaded.relationships.find(x=>x.id===id);assert.ok(r);assert.ok(String(r.weight).length);}});

test('persisted invalid Activity relationships are reported instead of silently accepted',()=>{const{p,outside,initial}=fixture();const invalid=defaultRelationship('ControlFlow',outside.id,initial.id,'activity');p.relationships.push(invalid);const issues=activityRelationshipIssues(p,invalid);assert.equal(issues.length,1);assert.equal(issues[0].code,'ACTIVITY_EDGE_ENDPOINTS');});

test('Allocate remains a first-class Activity relationship with stable persistence fields',()=>{const{p,inside,outside}=fixture();const allocate=defaultRelationship('Allocate',inside.id,outside.id,'activity');allocate.name='resource allocation';p.relationships.push(allocate);const loaded=normalizeProject(JSON.parse(JSON.stringify(p))),copy=loaded.relationships.find(r=>r.id===allocate.id);assert.equal(copy.kind,'Allocate');assert.equal(copy.stereotype,'allocate');assert.equal(copy.sourceId,inside.id);assert.equal(copy.targetId,outside.id);});
