import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {reparentActivityMember,synchronizeActivityRegionMembership,synchronizeActivityRegionPresentations,activityRegionFor} from '../public/src/activity-regions.js';
import {validateBehaviorConnection,reconnectActivityFlow} from '../public/src/behavior-model.js';
import {DIAGRAMS} from '../public/src/sysml-profile.js';
import {ACTIVITY_CORE_TYPES,ACTIVITY_FLOW_TYPES,validateActivityManifest} from '../public/src/activity-manifest.js';

function fixture(){const p=createProject('Full Activity'),root=p.root.id,activity=Object.assign(defaultElement('Activity',root),{id:'activity',name:'Process'}),region=Object.assign(defaultElement('InterruptibleActivityRegion','activity'),{id:'region',name:'Abortable'}),structured=Object.assign(defaultElement('StructuredActivityNode','activity'),{id:'structured',name:'Structured'}),expansion=Object.assign(defaultElement('ExpansionRegion','structured'),{id:'expansion',name:'Batch'}),inside=Object.assign(defaultElement('Action','region'),{id:'inside',name:'Work'}),outside=Object.assign(defaultElement('Action','activity'),{id:'outside',name:'After'});p.elements.push(activity,region,structured,expansion,inside,outside);const d={id:'act',name:'Process Activity',diagramType:'Activity Diagram',ownerId:root,contextId:'activity',nodes:[{id:'nr',elementId:'region',x:100,y:100,width:360,height:240},{id:'ns',elementId:'structured',x:520,y:100,width:360,height:240},{id:'ne',elementId:'expansion',x:550,y:140,width:280,height:150},{id:'ni',elementId:'inside',x:160,y:170,width:190,height:110},{id:'no',elementId:'outside',x:520,y:420,width:190,height:110}],edges:[]};p.diagrams.push(d);return{p,d,activity,region,structured,expansion,inside,outside}}

test('full Activity manifest includes structured regions and interrupting edge',()=>{const profile=DIAGRAMS['Activity Diagram'];assert.deepEqual(validateActivityManifest(profile.elements,profile.relationships),{valid:true,missingElements:[],missingRelationships:[]});for(const kind of ['StructuredActivityNode','ExpansionRegion','InterruptibleActivityRegion'])assert.ok(ACTIVITY_CORE_TYPES.includes(kind));assert.ok(ACTIVITY_FLOW_TYPES.includes('InterruptingEdge'));});

test('region membership is canonical semantic ownership with graphical parent migration',()=>{const{p,d,region,inside}=fixture();region.memberIds=[];d.nodes.find(n=>n.elementId==='inside').parentPresentationId=null;synchronizeActivityRegionMembership(p);synchronizeActivityRegionPresentations(p,d);assert.deepEqual(region.memberIds,['inside']);assert.equal(d.nodes.find(n=>n.elementId==='inside').parentPresentationId,'nr');assert.equal(activityRegionFor(p,inside.id).id,region.id);});

test('moving an Activity node into and out of a region updates semantic and presentation ownership',()=>{const{p,d,structured,outside}=fixture();let result=reparentActivityMember(p,d,outside.id,structured.id);assert.equal(result.changed,true);assert.equal(outside.ownerId,structured.id);assert.equal(d.nodes.find(n=>n.elementId==='outside').parentPresentationId,'ns');result=reparentActivityMember(p,d,outside.id,null);assert.equal(result.changed,true);assert.equal(outside.ownerId,'activity');assert.equal(d.nodes.find(n=>n.elementId==='outside').parentPresentationId,null);});

test('InterruptingEdge must originate inside an InterruptibleActivityRegion and leave it',()=>{const{p,inside,outside}=fixture();assert.equal(validateBehaviorConnection(p,'InterruptingEdge',inside.id,outside.id).valid,true);assert.equal(validateBehaviorConnection(p,'InterruptingEdge',outside.id,inside.id).valid,false);const same=Object.assign(defaultElement('Action','region'),{id:'same',name:'Same region'});p.elements.push(same);assert.equal(validateBehaviorConnection(p,'InterruptingEdge',inside.id,same.id).valid,false);});

test('InterruptingEdge reconnect uses semantic IDs and rejects invalid region direction',()=>{const{p,d,inside,outside}=fixture();const rel=defaultRelationship('InterruptingEdge',inside.id,outside.id,'activity');p.relationships.push(rel);const sourceNode=d.nodes.find(n=>n.elementId===inside.id),targetNode=d.nodes.find(n=>n.elementId===outside.id);d.edges.push({id:'edge',relationshipId:rel.id,sourceNodeId:sourceNode.id,targetNodeId:targetNode.id});assert.equal(reconnectActivityFlow(p,d,rel,'target',targetNode.id).semanticId,outside.id);assert.throws(()=>reconnectActivityFlow(p,d,rel,'source',targetNode.id),/InterruptingEdge/);});

test('save/reload normalization preserves structured containment and region configuration',()=>{const{p,d,region,structured,expansion}=fixture();region.documentation='interruptible';structured.mustIsolate=true;expansion.expansionMode='parallel';const loaded=normalizeProject(JSON.parse(JSON.stringify(p)));assert.equal(loaded.elements.find(e=>e.id==='structured').mustIsolate,true);assert.equal(loaded.elements.find(e=>e.id==='expansion').expansionMode,'parallel');assert.deepEqual(loaded.elements.find(e=>e.id==='region').memberIds,['inside']);assert.equal(loaded.diagrams[0].nodes.find(n=>n.elementId==='inside').parentPresentationId,'nr');});
