import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {resolveActivityEndpoint,validateBehaviorConnection,initializeBehaviorElement,validateActivityReference,reconnectActivityFlow} from '../public/src/behavior-model.js';
import {ACTIVITY_CORE_TYPES,ACTIVITY_FLOW_TYPES,validateActivityManifest} from '../public/src/activity-manifest.js';
import {DIAGRAMS} from '../public/src/sysml-profile.js';
const add=(p,kind,id,owner,typeRef='')=>{const e=Object.assign(defaultElement(kind,owner),{id,name:id,typeRef,carriedTypeId:typeRef});p.elements.push(e);return e};
function fixture(){const p=createProject('Activity'),activity=add(p,'Activity','activity',p.root.id),diagram={id:'act-d',diagramType:'Activity Diagram',ownerId:p.root.id,contextId:activity.id,nodes:[],edges:[]};p.diagrams.push(diagram);return{p,activity,diagram}}
test('authoritative Activity manifest reconciles the qualified production palette',()=>{const profile=DIAGRAMS['Activity Diagram'];assert.deepEqual(validateActivityManifest(profile.elements,profile.relationships),{valid:true,missingElements:[],missingRelationships:[]});for(const kind of ACTIVITY_CORE_TYPES)assert.ok(profile.elements.includes(kind),kind);for(const kind of ACTIVITY_FLOW_TYPES)assert.ok(profile.relationships.includes(kind),kind);for(const omitted of ['StructuredActivityNode','ExpansionRegion','InterruptibleActivityRegion'])assert.ok(!profile.elements.includes(omitted))});
test('canonical resolver maps multiple presentations to one semantic endpoint',()=>{const{p,activity,diagram}=fixture(),action=add(p,'Action','action',activity.id);diagram.nodes.push({id:'presentation-a',elementId:action.id},{id:'presentation-b',elementId:action.id});for(const id of ['presentation-a','presentation-b']){const result=resolveActivityEndpoint(p,diagram,id,'Source endpoint');assert.equal(result.semanticId,action.id);assert.notEqual(result.presentationId,result.semanticId)}assert.throws(()=>resolveActivityEndpoint(p,diagram,{id:'missing'},'Target endpoint'),/Target endpoint presentation missing/)});
test('ControlFlow validates control-node direction before mutation',()=>{const{p,activity}=fixture(),initial=add(p,'InitialNode','initial',activity.id),action=add(p,'Action','action',activity.id),final=add(p,'ActivityFinalNode','final',activity.id),flowFinal=add(p,'FlowFinalNode','flow-final',activity.id);assert.equal(validateBehaviorConnection(p,'ControlFlow',initial.id,action.id).valid,true);assert.match(validateBehaviorConnection(p,'ControlFlow',action.id,initial.id).message,/InitialNode/);assert.match(validateBehaviorConnection(p,'ControlFlow',final.id,action.id).message,/cannot be the source/);assert.match(validateBehaviorConnection(p,'ControlFlow',flowFinal.id,action.id).message,/cannot be the source/)});
test('ObjectFlow requires directed typed pins and evaluates stable-ID generalization',()=>{const{p,activity}=fixture(),general=add(p,'DataType','general',p.root.id),specific=add(p,'DataType','specific',p.root.id),action=add(p,'Action','action',activity.id),out=add(p,'OutputPin','out',action.id,specific.id),input=add(p,'InputPin','in',action.id,general.id);p.relationships.push(defaultRelationship('Generalization',specific.id,general.id,p.root.id));assert.equal(validateBehaviorConnection(p,'ObjectFlow',out.id,input.id).valid,true);const unrelated=add(p,'DataType','unrelated',p.root.id),bad=add(p,'InputPin','bad',action.id,unrelated.id),before=JSON.stringify(p);const verdict=validateBehaviorConnection(p,'ObjectFlow',out.id,bad.id);assert.equal(verdict.valid,false);assert.match(verdict.message,/no common compatible classifier/);assert.equal(JSON.stringify(p),before);assert.match(validateBehaviorConnection(p,'ObjectFlow',input.id,out.id).message,/source/)});
test('activity semantic defaults survive save/reload without identity loss',()=>{const{p,activity}=fixture(),behavior=add(p,'Activity','called',p.root.id),call=initializeBehaviorElement(Object.assign(defaultElement('CallBehaviorAction',activity.id),{id:'call',referencedBehaviorId:behavior.id})),partition=initializeBehaviorElement(Object.assign(defaultElement('ActivityPartition',activity.id),{id:'lane',orientation:'vertical'}));p.elements.push(call,partition);const loaded=normalizeProject(JSON.parse(JSON.stringify(p)));assert.equal(loaded.elements.find(e=>e.id==='call').referencedBehaviorId,behavior.id);assert.equal(loaded.elements.find(e=>e.id==='lane').orientation,'vertical')});
test('production app uses guided Activity references and native notation',async()=>{const app=await readFile(new URL('../public/src/app.js',import.meta.url),'utf8');for(const token of ['resolveActivityEndpoint','Create Call Behavior Action','Pin type',"e.kind==='ActivityPartition'","e.orientation==='vertical'"])assert.ok(app.includes(token),token);assert.ok(!app.includes("prompt('Called Behavior"))});
test('every specialized advertised Action requires and retains a stable semantic reference',()=>{const{p,activity}=fixture(),behavior=add(p,'Activity','called',p.root.id),block=add(p,'Block','block',p.root.id),operation=add(p,'Operation','operation',block.id),signal=add(p,'Signal','signal',p.root.id),event=add(p,'Event','event',p.root.id),cases=[['CallBehaviorAction','referencedBehaviorId',behavior.id],['CallOperationAction','referencedOperationId',operation.id],['SendSignalAction','signalId',signal.id],['AcceptEventAction','eventId',event.id]];for(const[kind,field,id]of cases){const element=initializeBehaviorElement(Object.assign(defaultElement(kind,activity.id),{id:`${kind}-id`,[field]:id}));p.elements.push(element);assert.equal(validateActivityReference(p,element),'');const missing={...element,[field]:''};assert.match(validateActivityReference(p,missing),/requires/)}});
test('Activity Parameter Nodes use same-Activity Parameters and explicit directions',()=>{const{p,activity}=fixture(),type=add(p,'DataType','type',p.root.id),parameter=Object.assign(defaultElement('Parameter',activity.id),{id:'parameter',name:'payload',typeRef:type.id,direction:'in'});p.elements.push(parameter);const node=initializeBehaviorElement(Object.assign(defaultElement('ActivityParameterNode',activity.id),{id:'apn',parameterId:parameter.id,typeRef:type.id,direction:'in'}));p.elements.push(node);assert.equal(validateActivityReference(p,node),'');const otherActivity=add(p,'Activity','other',p.root.id),other=Object.assign(defaultElement('Parameter',otherActivity.id),{id:'other-parameter'});p.elements.push(other);assert.match(validateActivityReference(p,{...node,parameterId:other.id}),/owned by its Activity/) });
test('Activity flow reconnection validates before mutation and preserves flow identity',()=>{const{p,activity,diagram}=fixture(),a=add(p,'Action','a',activity.id),b=add(p,'Action','b',activity.id),initial=add(p,'InitialNode','initial',activity.id),flow=Object.assign(defaultRelationship('ControlFlow',initial.id,a.id,activity.id),{id:'flow'});p.relationships.push(flow);diagram.nodes.push({id:'initial-p',elementId:initial.id},{id:'a-p',elementId:a.id},{id:'b-p',elementId:b.id});const resolved=reconnectActivityFlow(p,diagram,flow,'target','b-p');assert.equal(resolved.semanticId,b.id);assert.equal(flow.id,'flow');assert.equal(flow.targetId,b.id);const before=structuredClone(flow);assert.throws(()=>reconnectActivityFlow(p,diagram,flow,'target','initial-p'),/InitialNode/);assert.deepEqual(flow,before)});
