import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {behaviorRelationshipLabel,initializeBehaviorRelationship,INTERACTION_OPERATORS,MESSAGE_KINDS,validateBehaviorConnection,validLifelineRepresentation} from '../public/src/behavior-model.js';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {applyOperation} from '../public/src/operations.js';
import {canShowElementOnDiagram,showElementOnDiagram} from '../public/src/diagram-presentations.js';
import {lifelineGeometry,messageGeometry,nextMessageOrder,resizeExecutionSpecification} from '../public/src/sequence-interactions.js';

function sequenceFixture(){const project=createProject('Behavior'),interaction=defaultElement('Interaction',project.root.id),actor=defaultElement('Actor',project.root.id),block=defaultElement('Block',project.root.id),left=defaultElement('Lifeline',interaction.id),right=defaultElement('Lifeline',interaction.id);Object.assign(interaction,{id:'interaction'});Object.assign(actor,{id:'actor'});Object.assign(block,{id:'block'});Object.assign(left,{id:'left',representedElementId:'actor'});Object.assign(right,{id:'right',representedElementId:'block'});project.elements.push(interaction,actor,block,left,right);project.diagrams.push({id:'sequence',diagramType:'Sequence Diagram',ownerId:project.root.id,contextId:'interaction',nodes:[{id:'left-node',elementId:'left',x:100,y:30,width:140,height:45,timelineEndY:700},{id:'right-node',elementId:'right',x:430,y:30,width:140,height:45,timelineEndY:700}],edges:[]});return normalizeProject(project)}

test('behavior identity, references, and relationship details normalize independently from presentations',()=>{const project=sequenceFixture(),left=project.elements.find(item=>item.id==='left');assert.equal(left.representedElementId,'actor');assert.equal(validLifelineRepresentation(project,left.representedElementId),true);assert.notEqual(project.diagrams[0].nodes[0].id,left.id);for(const kind of MESSAGE_KINDS){const relationship=initializeBehaviorRelationship({kind:'Message',messageSort:kind,sourceId:'left',targetId:'right'});assert.equal(relationship.messageSort,kind);assert.equal(relationship.direction,'sourceToTarget')}assert.deepEqual(JSON.parse(JSON.stringify(project)).elements.find(item=>item.id==='left').representedElementId,'actor')});

test('lifelines move horizontally, resize independently, and messages stay attached by presentation ID',()=>{const project=sequenceFixture(),diagram=project.diagrams[0],left=diagram.nodes[0],relationship=defaultRelationship('Message','left','right','interaction'),edge={id:'message-node',relationshipId:relationship.id,sourceNodeId:'left-node',targetNodeId:'right-node',occurrenceY:180};diagram.edges.push(edge);project.relationships.push(relationship);left.x=220;assert.equal(messageGeometry(diagram,edge,relationship).path[0].x,290);applyOperation(project,{type:'resize-lifeline-timeline',diagramId:'sequence',nodeId:'left-node',timelineEndY:900});assert.equal(lifelineGeometry(left).timelineEndY,900);assert.equal(left.elementId,'left')});

test('message geometry supports call kinds, self, lost, found, ordering, and endpoint replay without direction inference',()=>{const project=sequenceFixture(),diagram=project.diagrams[0];for(const [index,kind] of MESSAGE_KINDS.entries()){const relationship=defaultRelationship('Message','left','right','interaction');Object.assign(relationship,{id:`m-${kind}`,messageSort:kind,sequenceOrder:index+1});const edge={id:`e-${kind}`,relationshipId:relationship.id,sourceNodeId:'left-node',targetNodeId:'right-node',occurrenceY:120+index*30};if(kind==='lost'){relationship.targetId='';delete edge.targetNodeId;edge.lostAnchor={x:620,y:edge.occurrenceY}}if(kind==='found'){relationship.sourceId='';delete edge.sourceNodeId;edge.foundAnchor={x:50,y:edge.occurrenceY}}assert.ok(messageGeometry(diagram,edge,relationship),kind);project.relationships.push(relationship);diagram.edges.push(edge)}const self=defaultRelationship('Message','left','left','interaction');assert.equal(messageGeometry(diagram,{sourceNodeId:'left-node',targetNodeId:'left-node',occurrenceY:500},self).self,true);assert.equal(nextMessageOrder(project,diagram),9);applyOperation(project,{type:'reconnect-message',diagramId:'sequence',edgeId:'e-synchronous',relationshipId:'m-synchronous',end:'target',nodeId:'left-node',elementId:'left'});assert.equal(project.relationships.find(item=>item.id==='m-synchronous').sourceId,'left');assert.equal(project.relationships.find(item=>item.id==='m-synchronous').targetId,'left')});

test('execution specifications and operands require sequence graphical parents and persist geometry',()=>{const project=sequenceFixture(),diagram=project.diagrams[0],execution=defaultElement('ExecutionSpecification','interaction'),fragment=defaultElement('CombinedFragment','interaction'),operand=defaultElement('InteractionOperand',fragment.id);Object.assign(execution,{id:'execution',coveredLifelineId:'left'});Object.assign(fragment,{id:'fragment',fragmentOperator:'strict'});Object.assign(operand,{id:'operand',ownerId:'fragment',guard:'ready'});project.elements.push(execution,fragment,operand);const fragmentNode=showElementOnDiagram(project,'fragment','sequence',{x:80,y:200}).node;assert.equal(canShowElementOnDiagram(project,'execution','sequence',{point:{x:150,y:250},targetNode:fragmentNode}).valid,false);const executionResult=showElementOnDiagram(project,'execution','sequence',{x:170,y:220},{targetNode:diagram.nodes[0]});assert.equal(executionResult.node.parentPresentationId,'left-node');resizeExecutionSpecification(executionResult.node,20);assert.equal(executionResult.node.height,35);const operandResult=showElementOnDiagram(project,'operand','sequence',{x:100,y:270},{targetNode:fragmentNode});assert.equal(operandResult.node.parentPresentationId,fragmentNode.id);assert.equal(project.elements.find(item=>item.id==='operand').ownerId,'fragment');const loaded=normalizeProject(JSON.parse(JSON.stringify(project)));assert.equal(loaded.diagrams[0].nodes.find(item=>item.id===operandResult.node.id).parentPresentationId,fragmentNode.id);assert.ok(INTERACTION_OPERATORS.includes(loaded.elements.find(item=>item.id==='fragment').fragmentOperator))});

test('activity, transition, include, and extend retain distinct endpoint and label semantics',()=>{const project=createProject(),activity=defaultElement('Activity',project.root.id),action=defaultElement('Action',activity.id),object=defaultElement('ObjectNode',activity.id),machine=defaultElement('StateMachine',project.root.id),state=defaultElement('State',machine.id),final=defaultElement('FinalState',machine.id),trigger=defaultElement('Trigger',state.id),a=defaultElement('UseCase',project.root.id),b=defaultElement('UseCase',project.root.id);Object.assign(action,{id:'action'});Object.assign(object,{id:'object'});Object.assign(state,{id:'state'});Object.assign(final,{id:'final'});Object.assign(trigger,{id:'trigger',name:'timeout'});Object.assign(a,{id:'a'});Object.assign(b,{id:'b'});project.elements.push(activity,action,object,machine,state,final,trigger,a,b);assert.equal(validateBehaviorConnection(project,'ControlFlow','action','object').valid,false);assert.equal(validateBehaviorConnection(project,'ObjectFlow','action','object').valid,true);assert.equal(validateBehaviorConnection(project,'Transition','final','state').valid,false);const transition=initializeBehaviorRelationship({kind:'Transition',sourceId:'state',targetId:'final',triggerIds:['trigger'],guard:'ready',effect:'stop()'});assert.equal(behaviorRelationshipLabel(project,transition),'timeout [ready] / stop()');const include=initializeBehaviorRelationship({kind:'Include',sourceId:'a',targetId:'b'}),extend=initializeBehaviorRelationship({kind:'Extend',sourceId:'a',targetId:'b'});assert.equal(include.direction,'sourceToTarget');assert.equal(extend.direction,'sourceToTarget');assert.equal(include.stereotype,'include');assert.equal(extend.stereotype,'extend')});

test('behavior palette, properties, renderers, importer, and focus-safe commits share existing architecture',async()=>{const [app,importer]=await Promise.all([readFile(new URL('../public/src/app.js',import.meta.url),'utf8'),readFile(new URL('../public/src/importer.js',import.meta.url),'utf8')]);assert.match(app,/ExecutionSpecification','InteractionOperand/);assert.match(app,/MESSAGE_KINDS\.map/);assert.match(app,/INTERACTION_OPERATORS\.map/);assert.match(app,/Referenced behavior/);assert.match(app,/eventType|,'blur'/);assert.match(importer,/representedElementId/);assert.match(importer,/sequenceOrder/);assert.match(importer,/sourceNodeId/);assert.match(importer,/Occurrence Y/)});
