import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {applyOperation} from '../public/src/operations.js';
import {ensureIBDContextPresentation,visibleIBDNodes} from '../public/src/ibd-engine.js';
import {canShowElementOnDiagram,defaultPresentationSize,diagramPointFromClient,edgeAutoPanDelta,findPresentation,removePresentation,showElementOnDiagram,showRelationshipOnDiagram} from '../public/src/diagram-presentations.js';

const diagram=(id,type,ownerId,contextId=ownerId)=>({id,externalId:id,name:id,diagramType:type,ownerId,contextId,nodes:[],edges:[]});
function model(){const p=createProject('Drag model'),block=defaultElement('Block',p.root.id),requirement=defaultElement('Requirement',p.root.id),actor=defaultElement('Actor',p.root.id);Object.assign(block,{id:'block-1',name:'transmitterSystem'});Object.assign(requirement,{id:'req-1',name:'Transmit requirement'});Object.assign(actor,{id:'actor-1',name:'Operator'});p.elements.push(block,requirement,actor);p.diagrams.push(diagram('bdd-1','Block Definition Diagram',p.root.id),diagram('bdd-2','Block Definition Diagram',p.root.id),diagram('req-d','Requirement Diagram',p.root.id),diagram('uc-d','Use Case Diagram',p.root.id));return normalizeProject(p)}

test('containment placement creates presentations only and preserves stable semantic identity across diagrams',()=>{const p=model(),count=p.elements.length,a=showElementOnDiagram(p,'block-1','bdd-1',{x:300,y:200}),b=showElementOnDiagram(p,'block-1','bdd-2',{x:500,y:350});assert.equal(a.created,true);assert.equal(b.created,true);assert.equal(p.elements.length,count);assert.equal(a.node.elementId,'block-1');assert.equal(b.node.elementId,'block-1');assert.notEqual(a.node.id,b.node.id);p.elements.find(e=>e.id==='block-1').name='Renamed transmitter';assert.equal(findPresentation(p,'block-1','bdd-1').elementId,'block-1');assert.equal(findPresentation(p,'block-1','bdd-2').elementId,'block-1');assert.equal(p.elements.find(e=>e.id===a.node.elementId).name,'Renamed transmitter')});

test('remove, undo, redo, and JSON reload affect only presentation records',()=>{const p=model(),created=showElementOnDiagram(p,'block-1','bdd-1',{x:200,y:150}).node,snapshot=structuredClone(created);assert.equal(removePresentation(p,'bdd-1',created.id).elementId,'block-1');assert.ok(p.elements.some(e=>e.id==='block-1'));const redone=applyOperation(p,{type:'add-presentation',diagramId:'bdd-1',node:snapshot});assert.equal(findPresentation(redone,'block-1','bdd-1').x,snapshot.x);const undone=applyOperation(redone,{type:'remove-presentation',diagramId:'bdd-1',nodeId:snapshot.id});assert.equal(findPresentation(undone,'block-1','bdd-1'),null);const loaded=normalizeProject(JSON.parse(JSON.stringify(applyOperation(undone,{type:'add-presentation',diagramId:'bdd-1',node:snapshot}))));assert.deepEqual(findPresentation(loaded,'block-1','bdd-1'),snapshot)});

test('drop coordinates account for canvas offset, scrolling embodied by its rect, and zoom',()=>{assert.deepEqual(diagramPointFromClient({clientX:460,clientY:330},{left:60,top:30},2),{x:200,y:150});assert.deepEqual(diagramPointFromClient({clientX:260,clientY:180},{left:-140,top:-120},2),{x:200,y:150})});

test('central profile compatibility accepts Block, Requirement, and Actor on appropriate diagrams and detects duplicates',()=>{const p=model();assert.equal(canShowElementOnDiagram(p,'block-1','bdd-1').valid,true);assert.equal(canShowElementOnDiagram(p,'req-1','req-d').valid,true);assert.equal(canShowElementOnDiagram(p,'actor-1','uc-d').valid,true);assert.equal(canShowElementOnDiagram(p,'actor-1','req-d').valid,false);showElementOnDiagram(p,'block-1','bdd-1',{x:100,y:100});const duplicate=canShowElementOnDiagram(p,'block-1','bdd-1');assert.equal(duplicate.code,'already-present');assert.ok(duplicate.existing)});

test('IBD properties and ports retain ownership and require valid graphical context',()=>{const p=model(),block=p.elements.find(e=>e.id==='block-1'),part=defaultElement('PartProperty',block.id),port=defaultElement('ProxyPort',block.id);Object.assign(part,{id:'part-1',name:'tx'});Object.assign(port,{id:'port-1',name:'rf'});p.elements.push(part,port);const ibd=diagram('ibd-1','Internal Block Diagram',block.ownerId,block.id);p.diagrams.push(ibd);const context=ensureIBDContextPresentation(p,ibd);const partResult=showElementOnDiagram(p,'part-1','ibd-1',{x:250,y:220});assert.equal(partResult.created,true);assert.equal(partResult.node.elementId,'part-1');const invalidPort=canShowElementOnDiagram(p,'port-1','ibd-1',{point:{x:2000,y:2000}});assert.equal(invalidPort.code,'port-owner-required');const portResult=showElementOnDiagram(p,'port-1','ibd-1',{x:context.x+context.width,y:context.y+200});assert.equal(portResult.created,true);assert.equal(portResult.node.boundaryOwnerNodeId,context.id);assert.equal(p.elements.filter(e=>e.id==='port-1').length,1)});

test('existing semantic relationships display only when endpoint presentations exist',()=>{const p=model(),other=defaultElement('Block',p.root.id);other.id='block-2';p.elements.push(other);const relationship=defaultRelationship('Association','block-1','block-2',p.root.id);relationship.id='relationship-1';p.relationships.push(relationship);showElementOnDiagram(p,'block-1','bdd-1',{x:100,y:100});assert.equal(showRelationshipOnDiagram(p,'relationship-1','bdd-1').code,'missing-endpoints');showElementOnDiagram(p,'block-2','bdd-1',{x:400,y:100});const shown=showRelationshipOnDiagram(p,'relationship-1','bdd-1');assert.equal(shown.created,true);assert.equal(shown.edge.relationshipId,'relationship-1');assert.equal(p.relationships.length,1)});

test('edge auto-pan is gentle and presentation defaults are notation-specific',()=>{assert.deepEqual(edgeAutoPanDelta({x:5,y:295},{left:0,top:0,right:500,bottom:300}),{x:-12.75,y:12.75});assert.deepEqual(edgeAutoPanDelta({x:250,y:150},{left:0,top:0,right:500,bottom:300}),{x:0,y:0});assert.notDeepEqual(defaultPresentationSize('Actor'),defaultPresentationSize('Requirement'));assert.notDeepEqual(defaultPresentationSize('ProxyPort'),defaultPresentationSize('Block'))});

test('imported semantic elements use the identical presentation command and schema',()=>{const p=model(),imported={...defaultElement('Block',p.root.id),id:'imported-block',externalId:'CATIA-42',name:'Imported'};p.elements.push(imported);const result=showElementOnDiagram(p,imported.id,'bdd-1',{x:333,y:222});assert.equal(result.node.elementId,imported.id);assert.equal(result.node.source,'containment');assert.equal(p.elements.find(e=>e.externalId==='CATIA-42').id,'imported-block')});


test('containment DOM integration uses stable structured payloads and complete drop lifecycle',async()=>{const source=await readFile(new URL('../public/src/app.js',import.meta.url),'utf8');for(const event of ['dragenter','dragover','dragleave','drop'])assert.ok(source.includes(`addEventListener('${event}'`),event);assert.match(source,/application\/x-sysml-containment\+json/);assert.match(source,/semanticElementId:id/);assert.match(source,/source:'containment'/);assert.match(source,/type:'add-presentation'/);assert.match(source,/Show on Active Diagram/);assert.match(source,/Reveal on Active Diagram/)});

test('owned pins are visible only when dropped on their owning Action',()=>{const p=model(),activity=defaultElement('Activity',p.root.id),action=defaultElement('Action',activity.id),pin=defaultElement('InputPin',action.id);Object.assign(activity,{id:'activity'});Object.assign(action,{id:'action'});Object.assign(pin,{id:'pin',ownerId:'action'});p.elements.push(activity,action,pin);const d=diagram('activity-d','Activity Diagram',p.root.id,activity.id);d.nodes.push({id:'action-node',elementId:'action',x:100,y:100,width:190,height:110});p.diagrams.push(d);assert.equal(canShowElementOnDiagram(p,'pin','activity-d',{point:{x:500,y:500}}).code,'graphical-owner-required');const result=showElementOnDiagram(p,'pin','activity-d',{x:100,y:150},{targetNode:d.nodes[0]});assert.equal(result.created,true);assert.equal(result.node.parentPresentationId,'action-node');assert.equal(result.node.boundary,true);assert.ok(result.node.width>0&&result.node.height>0)});

test('IBD accepts explicitly placed Blocks and Part Properties without confusing the frame context',()=>{const p=model(),owner=p.elements.find(element=>element.id==='block-1'),part=defaultElement('PartProperty',owner.id);Object.assign(part,{id:'manual-part',name:'controller',typeRef:owner.id});p.elements.push(part);const ibd=diagram('manual-ibd','Internal Block Diagram',owner.ownerId,owner.id);p.diagrams.push(ibd);const context=ensureIBDContextPresentation(p,ibd);assert.equal(findPresentation(p,owner.id,ibd.id),null);const blockResult=showElementOnDiagram(p,owner.id,ibd.id,{x:420,y:180});const partResult=showElementOnDiagram(p,part.id,ibd.id,{x:180,y:180});assert.equal(blockResult.created,true);assert.equal(partResult.created,true);assert.equal(blockResult.node.elementId,owner.id);assert.equal(partResult.node.elementId,part.id);assert.notEqual(blockResult.node.id,context.id);assert.ok(visibleIBDNodes(ibd).some(node=>node.id===blockResult.node.id));assert.ok(visibleIBDNodes(ibd).some(node=>node.id===partResult.node.id))});
