import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {E01I_IBD_MANIFEST,validateE01IManifest} from '../public/src/e01i-ibd-manifest.js';import {E01I_IBD_CONTRACTS,E01I_GATES,validateE01IContracts} from '../public/src/e01i-ibd-contracts.js';
import {ensureIBDContextPresentation,createIBDPropertyPresentation,createIBDPortPresentation,resolveIBDEndpoint,configureIBDConnector,createItemFlow,updateItemFlow,validateIBD} from '../public/src/ibd-engine.js';import {reconnectConnectorEnd} from '../public/src/connector-ends.js';import {inventoryEntry,SUPPORTED_TYPE_INVENTORY} from '../public/src/supported-type-inventory.js';
const add=(p,kind,id,owner=p.root.id)=>{const e=Object.assign(defaultElement(kind,owner),{id,name:id});p.elements.push(e);return e};
function fixture(){const p=createProject('IBD'),owner=add(p,'Block','owner'),type=add(p,'Block','type'),iface=add(p,'InterfaceBlock','iface'),signal=add(p,'Signal','signal'),flow=add(p,'FlowProperty','flow',iface.id),part=add(p,'PartProperty','part',owner.id),reference=add(p,'ReferenceProperty','reference',owner.id),contextPort=add(p,'ProxyPort','context-port',owner.id),internalPort=add(p,'ProxyPort','internal-port',type.id),secondPort=add(p,'ProxyPort','second-port',type.id);flow.typeRef=signal.id;flow.direction='out';part.typeRef=type.id;reference.typeRef=type.id;contextPort.typeRef=iface.id;internalPort.typeRef=iface.id;secondPort.typeRef=iface.id;internalPort.isConjugated=true;secondPort.isConjugated=true;const d={id:'ibd',name:'Internal',diagramType:'Internal Block Diagram',ownerId:owner.id,contextId:owner.id,nodes:[],edges:[]};p.diagrams.push(d);const boundary=ensureIBDContextPresentation(p,d),partNode=createIBDPropertyPresentation(p,d,part.id),referenceNode=createIBDPropertyPresentation(p,d,reference.id),a=createIBDPortPresentation(p,d,contextPort.id,boundary),b=createIBDPortPresentation(p,d,internalPort.id,partNode),c=createIBDPortPresentation(p,d,secondPort.id,partNode,{side:'bottom'});return{p,d,owner,signal,partNode,referenceNode,a,b,c}}
test('authoritative IBD manifest includes palette, owned records, aliases, and pre-existing exclusions',()=>{assert.equal(validateE01IManifest(SUPPORTED_TYPE_INVENTORY),true);assert.equal(validateE01IContracts(),true);assert.ok(E01I_IBD_MANIFEST.some(x=>x.canonicalType==='ConnectorEnd'&&!x.paletteRequired));for(const kind of ['DirectedFeature','DistributedProperty','BoundReference','ConnectorProperty','ParticipantProperty','BindingConnector'])assert.equal(E01I_IBD_MANIFEST.find(x=>x.canonicalType===kind).currentSupportState,'explicitly-out-of-product-scope');assert.equal(Object.keys(E01I_IBD_CONTRACTS).length,22);assert.equal(E01I_GATES.length,32)});
test('assembly and delegation are authored connector classifications with stable first-class ends',()=>{const f=fixture(),assembly=defaultRelationship('Connector',f.partNode.elementId,f.referenceNode.elementId,f.owner.id);configureIBDConnector(f.p,f.d,assembly,f.partNode,f.referenceNode,'assembly');f.p.relationships.push(assembly);const delegation=defaultRelationship('DelegationConnector',f.a.elementId,f.b.elementId,f.owner.id);configureIBDConnector(f.p,f.d,delegation,f.a,f.b,'delegation');f.p.relationships.push(delegation);assert.equal(assembly.metaclass,'Connector');assert.equal(delegation.metaclass,'Connector');assert.equal(delegation.connectorKind,'delegation');assert.equal(delegation.connectorEnds.length,2);const endId=delegation.targetEndId;reconnectConnectorEnd(f.p,delegation.id,'target',{roleId:f.c.elementId,portId:f.c.elementId,endpointPath:f.c.endpointPath,propertyPath:f.c.propertyPath,presentationId:f.c.id});assert.equal(delegation.targetEndId,endId);assert.equal(delegation.targetId,f.c.elementId);assert.deepEqual(validateIBD(f.p,f.d),[])});
test('canonical endpoint resolution converts every presentation to its semantic stable identity',()=>{const f=fixture(),duplicate={...f.b,id:'second-presentation-of-internal-port',x:f.b.x+30};f.d.nodes.push(duplicate);for(const presentation of [f.a,f.b,duplicate]){const resolved=resolveIBDEndpoint(f.p,f.d,presentation.id,presentation===f.a?'source':'target');assert.equal(resolved.semanticId,presentation.elementId);assert.equal(resolved.element.kind,'ProxyPort');assert.notEqual(resolved.semanticId,presentation.id)}assert.equal(resolveIBDEndpoint(f.p,f.d,f.b.id).semanticId,resolveIBDEndpoint(f.p,f.d,duplicate.id).semanticId);assert.throws(()=>resolveIBDEndpoint(f.p,f.d,{id:'missing-node',elementId:'internal-port'},'source'),error=>error.field==='source'&&/presentation missing-node/.test(error.message));const masquerade={id:'fake-port-node',elementId:'signal'};f.d.nodes.push(masquerade);assert.throws(()=>resolveIBDEndpoint(f.p,f.d,masquerade,'target'),error=>error.field==='target'&&error.actualType==='Signal')});
test('ConnectorEnds contain semantic role and port IDs, never presentation IDs',()=>{const f=fixture(),connector=defaultRelationship('DelegationConnector',f.a.elementId,f.b.elementId,f.owner.id);configureIBDConnector(f.p,f.d,connector,f.a.id,f.b.id,'delegation');for(const end of connector.connectorEnds){assert.ok([f.a.elementId,f.b.elementId].includes(end.roleId));assert.equal(end.portId,end.roleId);assert.notEqual(end.roleId,end.presentationId);assert.ok([f.a.id,f.b.id].includes(end.presentationId))}});
test('ItemFlow retains stable connector and conveyed identities independent of routing geometry',()=>{const f=fixture(),connector=defaultRelationship('DelegationConnector',f.a.elementId,f.b.elementId,f.owner.id);configureIBDConnector(f.p,f.d,connector,f.a,f.b,'delegation');f.p.relationships.push(connector);const flow=createItemFlow(f.p,connector,f.signal.id,'targetToSource',{id:'flow'});connector.points=[{x:900,y:900}];assert.equal(flow.connectorId,connector.id);assert.deepEqual(flow.conveyedIds,[f.signal.id]);assert.equal(flow.direction,'targetToSource');updateItemFlow(f.p,flow.id,{direction:'bidirectional'});assert.equal(flow.direction,'bidirectional');assert.equal(validateIBD(f.p,f.d).length,0)});
test('normalization preserves semantic and presentation identities without geometry ownership inference',()=>{const f=fixture(),ownerId=f.p.elements.find(x=>x.id==='part').ownerId,beforeIds=f.d.nodes.map(x=>x.id),loaded=normalizeProject(JSON.parse(JSON.stringify(f.p)));loaded.diagrams[0].nodes.find(x=>x.elementId==='part').x=1000;normalizeProject(loaded);assert.equal(loaded.elements.find(x=>x.id==='part').ownerId,ownerId);assert.deepEqual(loaded.diagrams[0].nodes.map(x=>x.id),beforeIds)});
test('DelegationConnector inventory is independently promoted with maintained production evidence',()=>{const item=inventoryEntry('DelegationConnector','relationship');assert.equal(item.supportStatus,'complete');assert.ok(item.browserTests.includes('browser-tests/ibd-complete.spec.mjs'));assert.equal(item.metaclass,'Connector')});
