import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,defaultElement,normalizeProject} from '../public/src/model.js';
import {showElementOnDiagram,removePresentation} from '../public/src/diagram-presentations.js';
import {createStructuralTypingElement} from '../public/src/structural-typing.js';
import {elementCapabilityFor} from '../public/src/sysml/conformance-registry.js';
import {inventoryEntry} from '../public/src/supported-type-inventory.js';
import {resolvePresentation} from '../public/src/presentation-compatibility.js';
import {applyOperation} from '../public/src/operations.js';

test('production factory, dispatcher, renderer, and diagram paths support each structural typing element independently',()=>{const p=createProject('Production'),block=Object.assign(defaultElement('Block',p.root.id),{id:'block',name:'Vehicle'});p.elements.push(block);p.diagrams.push({id:'bdd',name:'BDD',diagramType:'Block Definition Diagram',ownerId:p.root.id,contextId:p.root.id,nodes:[],edges:[]},{id:'ibd',name:'IBD',diagramType:'Internal Block Diagram',ownerId:p.root.id,contextId:block.id,nodes:[],edges:[]});const data=createStructuralTypingElement(p,'DataType',{id:'data',name:'Real',ownerId:p.root.id}),value=createStructuralTypingElement(p,'ValueType',{id:'value',name:'Mass',ownerId:p.root.id}),property=createStructuralTypingElement(p,'ValueProperty',{id:'property',name:'mass',ownerId:block.id,typeRef:value.id});for(const element of [data,value]){const shown=showElementOnDiagram(p,element.id,'bdd',{x:40+p.diagrams[0].nodes.length*220,y:40});assert.equal(shown.created,true);assert.notEqual(resolvePresentation({semanticType:element.kind,diagramType:'Block Definition Diagram'}).rendererKey,'diagnostic-presentation')}const shown=showElementOnDiagram(p,property.id,'ibd',{x:80,y:80});assert.equal(shown.created,true);for(const kind of ['DataType','ValueType','ValueProperty']){assert.equal(inventoryEntry(kind).supportStatus,'complete');assert.equal(elementCapabilityFor(kind==='ValueProperty'?'Internal Block Diagram':'Block Definition Diagram',kind).maturity,'working')}});

test('presentation deletion is independent and operation replay preserves semantic identity',()=>{const p=createProject('Delete'),data=createStructuralTypingElement(p,'DataType',{id:'data',name:'Real',ownerId:p.root.id});p.diagrams.push({id:'bdd',name:'BDD',diagramType:'Block Definition Diagram',ownerId:p.root.id,contextId:p.root.id,nodes:[],edges:[]});const shown=showElementOnDiagram(p,data.id,'bdd',{x:10,y:10}),removed=removePresentation(p,'bdd',shown.node.id);assert.equal(removed.elementId,data.id);assert.equal(p.elements.some(e=>e.id===data.id),true);applyOperation(p,{type:'set-property',targetType:'element',targetId:data.id,property:'name',value:'Number'});assert.equal(p.elements.find(e=>e.id==='data').name,'Number');assert.equal(normalizeProject(JSON.parse(JSON.stringify(p))).elements.find(e=>e.id==='data').id,'data')});
