import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,defaultElement,normalizeProject,qualifiedName} from '../public/src/model.js';
import {createE01S4Element,e01s4Issues,importE01S4,reorderE01S4Feature,E01S4_KINDS} from '../public/src/bdd-completion.js';
import {E01S4_BDD_SCOPE,validateE01S4Scope} from '../public/src/e01s4-bdd-scope.js';
import {E01S4_CONTRACTS,validateE01S4Contracts} from '../public/src/e01s4-bdd-contracts.js';
import {SUPPORTED_TYPE_INVENTORY} from '../public/src/supported-type-inventory.js';
test('exhaustive scope tracks direct, contextual, and explicitly non-adopted BDD candidates',()=>{assert.equal(validateE01S4Scope(),true);assert.ok(E01S4_BDD_SCOPE.length>20);for(const kind of E01S4_KINDS)assert.equal(E01S4_BDD_SCOPE.find(item=>item.canonicalType===kind)?.selectedForE01S4,true);for(const kind of ['Property','Port','DirectedFeature','DistributedProperty','BoundReference','ConnectorProperty','ParticipantProperty'])assert.ok(E01S4_BDD_SCOPE.find(item=>item.canonicalType===kind)?.normativeExclusion)});
test('independent contracts have normative metadata, three-level evidence, and complete inventory agreement',()=>{assert.equal(Object.keys(E01S4_CONTRACTS).length,E01S4_KINDS.length);assert.equal(validateE01S4Contracts(SUPPORTED_TYPE_INVENTORY),true)});
function fixture(){const p=createProject('E01S4');const block=defaultElement('Block',p.root.id);block.id='block';block.name='Vehicle';const signal=defaultElement('Signal',p.root.id);signal.id='signal';signal.name='Alarm';const data=defaultElement('DataType',p.root.id);data.id='real';data.name='Real';const value=defaultElement('ValueProperty','block');value.id='value';value.name='mass';value.typeRef='real';p.elements.push(block,signal,data,value);return normalizeProject(p)}
test('all concrete classifiers and real owned features preserve stable identity, references, names, and order',()=>{const p=fixture(),association=createE01S4Element(p,'AssociationBlock',{id:'ab',name:'Allocation',ownerId:p.root.id}),end1=createE01S4Element(p,'AssociationEnd',{id:'end-a',name:'whole',ownerId:'ab',typeRef:'block'}),end2=createE01S4Element(p,'AssociationEnd',{id:'end-b',name:'part',ownerId:'ab',typeRef:'block',multiplicityLower:'0',multiplicityUpper:'*',aggregation:'composite'}),constraint=createE01S4Element(p,'ConstraintBlock',{id:'cb',name:'MassLaw',ownerId:p.root.id,constraintExpression:'mass > 0'}),cp=createE01S4Element(p,'ConstraintProperty',{id:'cp',name:'law',ownerId:'block',typeRef:'cb'}),primitive=createE01S4Element(p,'PrimitiveType',{id:'integer',name:'Integer',ownerId:p.root.id}),library=createE01S4Element(p,'ModelLibrary',{id:'library',name:'Types',ownerId:p.root.id}),operation=createE01S4Element(p,'Operation',{id:'op',name:'compute',ownerId:'block'}),parameter=createE01S4Element(p,'Parameter',{id:'arg',name:'input',ownerId:'op',typeRef:'integer',direction:'in'}),ret=createE01S4Element(p,'Parameter',{id:'ret',name:'result',ownerId:'op',typeRef:'real',direction:'return'}),reception=createE01S4Element(p,'Reception',{id:'rx',name:'receiveAlarm',ownerId:'block',signalRef:'signal'}),instance=createE01S4Element(p,'InstanceSpecification',{id:'instance',name:'vehicle1',ownerId:p.root.id,classifierIds:['block']}),slot=createE01S4Element(p,'Slot',{id:'slot',name:'massValue',ownerId:'instance',definingFeatureId:'value',valueSpecification:{kind:'LiteralReal',value:'42'}});assert.equal(end1.metaclass,'Property');assert.equal(association.metaclass,'AssociationClass');assert.equal(constraint.stereotype,'constraintBlock');assert.equal(cp.typeRef,'cb');assert.equal(primitive.metaclass,'PrimitiveType');assert.equal(library.stereotype,'modelLibrary');assert.equal(parameter.typeRef,'integer');assert.equal(ret.direction,'return');assert.equal(reception.signalRef,'signal');assert.deepEqual(instance.classifierIds,['block']);assert.deepEqual(slot.valueSpecification,{kind:'LiteralReal',value:'42'});reorderE01S4Feature(p,'end-b',0);assert.deepEqual([end2.featureOrder,end1.featureOrder],[0,1]);association.name='AllocationRenamed';assert.equal(end1.id,'end-a');assert.equal(qualifiedName(p,'end-a').endsWith('AllocationRenamed::whole'),true);assert.deepEqual(e01s4Issues(p,end1),[])});
test('stable-ID import is deterministic and fatal failures roll back the whole transaction',()=>{const p=fixture(),records=[{id:'lib',kind:'ModelLibrary',name:'Library',ownerId:p.root.id},{id:'primitive',kind:'PrimitiveType',name:'Integer',ownerId:'lib'},{id:'cb',kind:'ConstraintBlock',name:'Rule',ownerId:'lib',constraintExpression:'x>0'},{id:'cp',kind:'ConstraintProperty',name:'rule',ownerId:'block',typeRef:'cb'},{id:'op',kind:'Operation',name:'calculate',ownerId:'block'},{id:'param',kind:'Parameter',name:'x',ownerId:'op',typeRef:'primitive',direction:'in'},{id:'rx',kind:'Reception',name:'alarm',ownerId:'block',signalRef:'signal'},{id:'inst',kind:'InstanceSpecification',name:'v1',ownerId:'lib',classifierIds:['block']},{id:'slot',kind:'Slot',name:'mass',ownerId:'inst',definingFeatureId:'value',valueSpecification:{kind:'LiteralReal',value:'4'}}];assert.equal(importE01S4(p,{elements:records}).applied,true);const ids=p.elements.map(e=>e.id).sort();assert.equal(importE01S4(p,{elements:records}).duplicates,0);assert.deepEqual(p.elements.map(e=>e.id).sort(),ids);const before=structuredClone(p);const failed=importE01S4(p,{elements:[{id:'bad',kind:'Reception',name:'bad',ownerId:'block',signalRef:'missing'}]});assert.equal(failed.applied,false);assert.deepEqual(p,before)});
