import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,defaultElement,normalizeProject,qualifiedName} from '../public/src/model.js';
import {createStructuralTypingElement,importStructuralTyping,normalizeStructuralTyping,structuralTypingIssues} from '../public/src/structural-typing.js';
import {propertyNotation} from '../public/src/notation-contracts.js';
import {getCompartmentRows,minimumNodeHeight} from '../public/src/notation.js';

function fixture(){const project=createProject('Typing');const block=Object.assign(defaultElement('Block',project.root.id),{id:'block',name:'Vehicle'}),unit=Object.assign(defaultElement('Unit',project.root.id),{id:'unit-kg',name:'kg'}),quantity=Object.assign(defaultElement('QuantityKind',project.root.id),{id:'quantity-mass',name:'Mass'});project.elements.push(block,unit,quantity);project.diagrams.push({id:'bdd',name:'Typing BDD',diagramType:'Block Definition Diagram',ownerId:project.root.id,contextId:project.root.id,nodes:[],edges:[]});return{project,block,unit,quantity}}

test('DataType and ValueType use the correct metaclass, stereotype, ownership, identity, and qualified names',()=>{const{project}=fixture(),data=createStructuralTypingElement(project,'DataType',{id:'data',name:'Real',ownerId:project.root.id}),value=createStructuralTypingElement(project,'ValueType',{id:'mass',name:'MassValue',ownerId:project.root.id,unitRef:'unit-kg',quantityKindRef:'quantity-mass'});assert.deepEqual([data.metaclass,data.stereotype,value.metaclass,value.stereotype],['DataType','','DataType','valueType']);const ids=[data.id,value.id];data.name='Number';value.name='Weight';assert.deepEqual([data.id,value.id],ids);assert.match(qualifiedName(project,value.id),/Typing::Weight$/);assert.deepEqual(structuralTypingIssues(project,value),[])});

test('ValueProperty keeps stable semantic typing through rename and valid reparenting and renders real notation',()=>{const{project,block}=fixture(),type=createStructuralTypingElement(project,'ValueType',{id:'mass-type',name:'Mass',ownerId:project.root.id}),property=createStructuralTypingElement(project,'ValueProperty',{id:'mass-property',name:'mass',ownerId:block.id,typeRef:type.id,multiplicityLower:'0',multiplicityUpper:'*',multiplicity:'0..*',defaultValue:'10',visibility:'private',isReadOnly:true});type.name='Weight';assert.equal(property.typeRef,'mass-type');assert.match(propertyNotation(project,property),/^-mass: Weight \[0\.\.\*\] = 10 \{readOnly\}$/);const block2=Object.assign(defaultElement('Block',project.root.id),{id:'block-2',name:'Payload'});project.elements.push(block2);property.ownerId=block2.id;assert.equal(qualifiedName(project,property.id),'Typing::Payload::mass');assert.deepEqual(structuralTypingIssues(project,property),[])});

test('ValueProperty compartment rows are semantic, ordered, and resize minimum remains readable',()=>{const{project,block}=fixture(),type=createStructuralTypingElement(project,'DataType',{id:'real',name:'Real',ownerId:project.root.id});createStructuralTypingElement(project,'ValueProperty',{id:'z',name:'temperature',ownerId:block.id,typeRef:type.id,defaultValue:'20'});const rows=getCompartmentRows(project,block,'values');assert.equal(rows.length,1);assert.equal(rows[0].id,'z');assert.match(String(rows[0].name),/temperature/);assert.ok(minimumNodeHeight(project,block)>72)});

test('field-specific validation rejects missing, deleted, incompatible, and unresolved semantic references',()=>{const{project,block}=fixture(),property=Object.assign(defaultElement('ValueProperty',block.id),{id:'bad',typeRef:'missing'});let issues=structuralTypingIssues(project,property);assert.equal(issues[0].field,'typeRef');assert.equal(issues[0].code,'VALUE_PROPERTY_TYPE_UNRESOLVED');property.typeRef=block.id;assert.equal(structuralTypingIssues(project,property).some(issue=>issue.code==='VALUE_PROPERTY_TYPE_INCOMPATIBLE'),true);const value=Object.assign(defaultElement('ValueType',project.root.id),{id:'bad-value',unitRef:'missing-unit'});assert.equal(structuralTypingIssues(project,value)[0].field,'unitRef')});

test('structured import and identical reimport preserve stable identities, fields, presentations, and prevent duplicates',()=>{const{project,block}=fixture(),payload={elements:[{id:'data',kind:'DataType',name:'Real',ownerId:project.root.id},{id:'value',kind:'ValueType',name:'MassValue',ownerId:project.root.id,unitRef:'unit-kg',quantityKindRef:'quantity-mass'},{id:'property',kind:'ValueProperty',name:'mass',ownerId:block.id,typeRef:'value',multiplicityLower:'0',multiplicityUpper:'1',multiplicity:'0..1',defaultValue:'12'}],presentations:[{id:'data-node',elementId:'data',diagramId:'bdd',x:20,y:30},{id:'value-node',elementId:'value',diagramId:'bdd',x:260,y:30}]};const first=importStructuralTyping(project,payload);assert.equal(first.applied,true);assert.equal(project.elements.filter(e=>['data','value','property'].includes(e.id)).length,3);const second=importStructuralTyping(project,payload);assert.equal(second.applied,true);assert.equal(second.created.length,0);assert.equal(project.elements.filter(e=>['data','value','property'].includes(e.id)).length,3);assert.equal(project.diagrams[0].nodes.length,2);const loaded=normalizeProject(JSON.parse(JSON.stringify(project))),property=loaded.elements.find(e=>e.id==='property');assert.equal(property.typeRef,'value');assert.equal(property.defaultValue,'12');assert.equal(property.multiplicity,'0..1')});

test('fatal import errors roll back the complete transaction with actionable fields',()=>{const{project}=fixture(),before=JSON.stringify(project),result=importStructuralTyping(project,{elements:[{id:'data',kind:'DataType',name:'Real',ownerId:project.root.id},{id:'bad',kind:'ValueProperty',name:'bad',ownerId:'missing-owner',typeRef:'data'}]});assert.equal(result.applied,false);assert.equal(result.field,'ownerId');assert.equal(JSON.stringify(project),before)});

test('conservative migration repairs profile metadata without inventing missing references',()=>{const{project}=fixture();project.elements.push({id:'legacy',kind:'ValueProperty',name:'legacy',ownerId:'block',typeRef:''});normalizeStructuralTyping(project);const legacy=project.elements.at(-1);assert.equal(legacy.metaclass,'Property');assert.equal(legacy.stereotype,'value');assert.equal(legacy.typeRef,'');assert.equal(structuralTypingIssues(project,legacy)[0].code,'VALUE_PROPERTY_TYPE_REQUIRED')});
