import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship} from '../public/src/model.js';
import {applyOperation,canRebaseOperation,deepClone} from '../public/src/operations.js';
import {acceptedOperation,createCollaborationOperation,migrateCollaborationOperation,validateCollaborationOperation} from '../public/src/collaboration-operation.js';
import {createRevision,elementHistory,replayOperations,revisionAt} from '../public/src/revision-journal.js';

test('formal operation records contain attributable, causal, target, value, undo, and status metadata',()=>{const project=createProject('Enterprise'),element=defaultElement('Block',project.root.id);project.elements.push(element);const record=createCollaborationOperation({type:'set-property',targetId:element.id,property:'name',value:'Vehicle',expectedValue:'Block'},{operationId:'op-1',projectId:project.id,branchId:'main',actorUserId:'user-1',actorDisplayName:'Ada',clientId:'client-1',parentRevisionId:'main:4',causalDependencies:['op-0'],undoMetadata:{operation:{type:'set-property',targetId:element.id,property:'name',value:'Block'}},source:'user'});assert.equal(validateCollaborationOperation(record).ok,true);assert.deepEqual({type:record.operationType,target:record.semanticTargetId,property:record.targetProperty,previous:record.previousValue,next:record.nextValue,status:record.status},{type:'set-property',target:element.id,property:'name',previous:'Block',next:'Vehicle',status:'pending'});assert.deepEqual(record.causalDependencies,['op-0'])});

test('legacy operation envelopes migrate and unsupported operations fail explicitly',()=>{const project=createProject(),record=migrateCollaborationOperation({operationId:'legacy-1',clientId:'client',author:'Grace',createdAt:'2026-08-06T00:00:00.000Z',operation:{type:'set-property',targetId:project.root.id,property:'name',value:'Migrated'}},{projectId:project.id,branchId:'main'});assert.equal(validateCollaborationOperation(record).ok,true);const unsupported=createCollaborationOperation({type:'silently-do-anything'},{projectId:project.id,clientId:'client'}),validation=validateCollaborationOperation(unsupported);assert.equal(validation.ok,false);assert.match(validation.errors.join(' '),/Unsupported operation type/)});

test('accepted journal operations replay deterministically and expose filtered element history',()=>{const project=createProject('History'),element=defaultElement('Block',project.root.id);element.id='vehicle';project.elements.push(element);const first=acceptedOperation(createCollaborationOperation({type:'set-property',targetId:element.id,property:'name',value:'Vehicle',expectedValue:'Block'},{operationId:'op-1',projectId:project.id,clientId:'c',actorUserId:'u',timestamp:'2026-08-06T00:00:00.000Z'}),{revisionId:'main:1',parentRevisionId:'main:0'}),second=acceptedOperation(createCollaborationOperation({type:'set-property',targetId:element.id,property:'documentation',value:'System context',expectedValue:''},{operationId:'op-2',projectId:project.id,clientId:'c',actorUserId:'u',timestamp:'2026-08-06T00:01:00.000Z'}),{revisionId:'main:2',parentRevisionId:'main:1'}),replayed=replayOperations(project,[first,second]);assert.equal(replayed.elements[0].name,'Vehicle');assert.equal(replayed.elements[0].documentation,'System context');assert.deepEqual(elementHistory([second,first],element.id).map(item=>item.operationId),['op-1','op-2'])});

test('revision records are immutable-shaped and time travel selectors find sequence, id, or date',()=>{const revisions=[createRevision({revisionId:'main:1',projectId:'p',branchId:'main',parentRevisionIds:['main:0'],author:{userId:'u'},createdAt:'2026-08-06T10:00:00.000Z',operationIds:['op-1']}),createRevision({revisionId:'main:2',projectId:'p',branchId:'main',parentRevisionIds:['main:1'],author:{userId:'u'},createdAt:'2026-08-06T11:00:00.000Z',operationIds:['op-2']})];revisions.forEach((item,index)=>item.sequence=index+1);assert.equal(revisionAt(revisions,2).revisionId,'main:2');assert.equal(revisionAt(revisions,'main:1').revisionId,'main:1');assert.equal(revisionAt(revisions,new Date('2026-08-06T10:30:00Z')).revisionId,'main:1')});

test('fine-grained relationship endpoint and presentation label operations rebase by independent scope',()=>{const project=createProject(),a=defaultElement('Block',project.root.id),b=defaultElement('Block',project.root.id),c=defaultElement('Block',project.root.id);project.elements.push(a,b,c);const relationship=defaultRelationship('Association',a.id,b.id,project.root.id);project.relationships.push(relationship);project.diagrams.push({id:'d',nodes:[],edges:[{id:'edge',relationshipId:relationship.id,labelX:10,labelY:20}]});const endpoint={type:'set-relationship-endpoint',relationshipId:relationship.id,end:'target',elementId:c.id,expectedValue:b.id},label={type:'move-edge-label',diagramId:'d',edgeId:'edge',labelX:30,labelY:40,expectedValue:{labelX:10,labelY:20}};assert.equal(canRebaseOperation(project,endpoint),true);assert.equal(canRebaseOperation(project,label),true);applyOperation(project,{type:'batch-operation',operations:[endpoint,label]});assert.equal(project.relationships[0].targetId,c.id);assert.deepEqual({x:project.diagrams[0].edges[0].labelX,y:project.diagrams[0].edges[0].labelY},{x:30,y:40})});

test('recovery replacements are explicitly rejected when recovery operations are disallowed',()=>{const project=createProject(),record=createCollaborationOperation({type:'replace-project',project:deepClone(project)},{projectId:project.id,clientId:'c',source:'user'});const validation=validateCollaborationOperation(record,{allowRecovery:false});assert.equal(validation.ok,false);assert.match(validation.errors.join(' '),/reserved/)});
