import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {normalizeConnectorEnds,reconnectConnectorEnd} from '../public/src/connector-ends.js';
import {removeRelationshipPresentation,deleteSemanticRelationship,restoreSemanticRelationship} from '../public/src/relationship-deletion.js';
import {presentExistingRelationship,migrateRelationshipPresentations} from '../public/src/relationship-persistence.js';
function fixture(){const p=createProject('F08Q2'),owner=Object.assign(defaultElement('Block',p.root.id),{id:'owner'}),type=Object.assign(defaultElement('Block',p.root.id),{id:'type'}),a=Object.assign(defaultElement('PartProperty','owner'),{id:'a',typeRef:'type'}),b=Object.assign(defaultElement('ReferenceProperty','owner'),{id:'b',typeRef:'type'}),c=Object.assign(defaultElement('ReferenceProperty','owner'),{id:'c',typeRef:'type'});p.elements.push(owner,type,a,b,c);const r=Object.assign(defaultRelationship('Connector','a','b','owner'),{id:'connector',sourceEndpointPath:['a'],targetEndpointPath:['b'],direction:'sourceToTarget'});normalizeConnectorEnds(r);p.relationships.push(r);p.diagrams=[{id:'d',diagramType:'Internal Block Diagram',ownerId:'owner',contextId:'owner',nodes:[{id:'na',elementId:'a'},{id:'nb',elementId:'b'},{id:'nc',elementId:'c'}],edges:[]}];const shown=presentExistingRelationship(p,'d','connector').edge;shown.labelPresentation={id:'label-e',x:10,y:20};shown.waypoints=[{id:'w',x:20,y:30,order:0}];shown.routingMode='manual';shown.sourceEndpointPath=['a'];shown.targetEndpointPath=['b'];return{p,r,shown}}
test('presentation deletion preserves semantics and restores exact identity and geometry',()=>{const{p,shown}=fixture(),before=structuredClone(shown),undo=removeRelationshipPresentation(p,'d',shown.id);assert.equal(p.relationships[0].id,'connector');assert.equal(p.diagrams[0].edges.length,0);p.diagrams[0].edges.splice(undo.index,0,undo.edge);assert.deepEqual(p.diagrams[0].edges[0],before)});
test('semantic deletion preserves endpoint elements and restores subordinate identities',()=>{const{p,r,shown}=fixture();p.relationships.push({id:'flow',kind:'ItemFlow',connectorId:r.id,direction:'targetToSource'});const snapshot=deleteSemanticRelationship(p,r.id);assert.equal(p.relationships.length,0);assert.deepEqual(p.elements.map(e=>e.id).sort(),['a','b','c','owner','type']);assert.equal(p.diagrams[0].edges.length,0);restoreSemanticRelationship(p,snapshot);assert.equal(p.relationships.find(x=>x.id==='connector').connectorEnds[0].id,r.connectorEnds[0].id);assert.equal(p.diagrams[0].edges[0].id,shown.id)});
test('containment presentation reuses semantics, rejects duplicates and ambiguous endpoints',()=>{const{p}=fixture();const count=p.relationships.length;assert.equal(presentExistingRelationship(p,'d','connector').created,false);assert.equal(p.relationships.length,count);p.diagrams[0].edges=[];p.diagrams[0].nodes.push({id:'na2',elementId:'a'});assert.throws(()=>presentExistingRelationship(p,'d','connector'),/unambiguous/);assert.equal(p.relationships.length,count)});
test('reconnection, JSON reload and migration preserve direction, endpoint and nested-path identities',()=>{const{p,r}=fixture(),id=r.connectorEnds[1].id;reconnectConnectorEnd(p,r.id,'target',{roleId:'c',endpointPath:['owner','c'],partWithPortPath:['owner'],presentationId:'nc'});const loaded=normalizeProject(JSON.parse(JSON.stringify(p))),next=loaded.relationships.find(x=>x.id===r.id),edge=loaded.diagrams[0].edges[0];assert.equal(next.targetEndId,id);assert.equal(next.direction,'sourceToTarget');assert.deepEqual(next.targetEndpointPath,['owner','c']);assert.equal(edge.waypoints[0].id,'w');assert.equal(edge.labelPresentation.id,'label-e')});
test('legacy ambiguity remains diagnosed and recoverable without geometry inference',()=>{const p={relationships:[],diagrams:[{id:'d',edges:[{id:'legacy',relationshipId:'missing',points:[{x:1,y:2},{x:3,y:4}]}]}]};migrateRelationshipPresentations(p);assert.equal(p.diagrams[0].edges[0].resolutionStatus,'unresolved');assert.match(p.diagrams[0].edges[0].diagnosticReason,/geometry was not used/);assert.equal(p.diagrams[0].edges[0].points.length,2)});
