import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {comparePorts} from '../public/src/interface-compatibility.js';
import {createIBDPropertyPresentation,createNestedPropertyPresentation,createIBDPortPresentation,ensureIBDContextPresentation,movePresentationTree,configureIBDConnector,createItemFlow} from '../public/src/ibd-engine.js';
import {formatPropertyPath,migrateLegacyPropertyPath,resolvePropertyPath,validatePropertyPath} from '../public/src/property-path.js';
import {applyOperation} from '../public/src/operations.js';

const add=(p,kind,name,owner=p.root.id)=>{const e=defaultElement(kind,owner);e.name=name;p.elements.push(e);return e};
function fixture(){const p=createProject('Nested'),context=add(p,'Block','Vehicle'),receiver=add(p,'Block','Receiver'),amp=add(p,'Block','Amplifier'),iface=add(p,'InterfaceBlock','DataInterface'),signal=add(p,'Signal','Status'),receiverPart=add(p,'PartProperty','receiver',context.id),ampPart=add(p,'PartProperty','amplifier',receiver.id),contextPort=add(p,'ProxyPort','status',context.id),ampPort=add(p,'ProxyPort','status',amp.id),flow=add(p,'FlowProperty','statusData',iface.id);receiverPart.typeRef=receiver.id;ampPart.typeRef=amp.id;contextPort.typeRef=iface.id;ampPort.typeRef=iface.id;flow.typeRef=signal.id;flow.direction='out';const d={id:'ibd',name:'Vehicle Internal',diagramType:'Internal Block Diagram',ownerId:p.root.id,contextId:context.id,nodes:[],edges:[]};p.diagrams.push(d);return{p,context,receiver,amp,iface,signal,receiverPart,ampPart,contextPort,ampPort,flow,d}}

test('nested presentations use stable paths and move with their parent',()=>{const f=fixture(),outer=createIBDPropertyPresentation(f.p,f.d,f.receiverPart.id,{x:100,y:100}),inner=createNestedPropertyPresentation(f.p,f.d,outer,f.ampPart.id,{relativeX:30,relativeY:45});assert.deepEqual(inner.propertyPath,[{propertyId:f.receiverPart.id,typeId:f.receiver.id},{propertyId:f.ampPart.id,typeId:f.amp.id}]);assert.equal(formatPropertyPath(f.p,inner.propertyPath),'receiver / amplifier');movePresentationTree(f.d,outer,20,15);assert.deepEqual([inner.x,inner.y],[150,160]);assert.throws(()=>createNestedPropertyPresentation(f.p,f.d,inner,f.receiverPart.id),/not valid/)});

test('structured paths resolve, detect stale types, and migrate legacy paths',()=>{const f=fixture(),path=[{propertyId:f.receiverPart.id,typeId:f.receiver.id},{propertyId:f.ampPart.id,typeId:f.amp.id}];assert.equal(resolvePropertyPath(f.p,f.context.id,path).classifier.id,f.amp.id);assert.equal(validatePropertyPath(f.p,f.context.id,path).valid,true);assert.equal(validatePropertyPath(f.p,f.context.id,[{...path[0],typeId:'stale'}]).code,'stale-type');assert.deepEqual(migrateLegacyPropertyPath(f.p,f.context.id,'receiver / amplifier').path,path)});

test('ProxyPort compatibility accounts for direction and conjugation',()=>{const f=fixture(),other=add(f.p,'ProxyPort','peer',f.amp.id);other.typeRef=f.iface.id;assert.equal(comparePorts(f.p,f.contextPort,other).compatible,false);other.isConjugated=true;assert.equal(comparePorts(f.p,f.contextPort,other).compatible,true);other.typeRef='missing';assert.equal(comparePorts(f.p,f.contextPort,other).status,'unresolved')});

test('nested delegation and ItemFlow persist through granular operations and reload',()=>{const f=fixture(),boundary=ensureIBDContextPresentation(f.p,f.d),outer=createIBDPropertyPresentation(f.p,f.d,f.receiverPart.id),inner=createNestedPropertyPresentation(f.p,f.d,outer,f.ampPart.id),a=createIBDPortPresentation(f.p,f.d,f.contextPort.id,boundary,{side:'left',offset:.2}),b=createIBDPortPresentation(f.p,f.d,f.ampPort.id,inner,{side:'bottom',offset:.7}),connector=defaultRelationship('DelegationConnector',a.elementId,b.elementId,f.context.id);f.ampPort.isConjugated=true;configureIBDConnector(f.p,f.d,connector,a,b,'delegation');f.p.relationships.push(connector);const flow=createItemFlow(f.p,connector,[f.signal.id],'sourceToTarget',{name:'statusData'});applyOperation(f.p,{type:'update-item-flow',itemFlowId:flow.id,changes:{conveyedClassifierIds:[f.signal.id],documentation:'telemetry'}});const restored=normalizeProject(JSON.parse(JSON.stringify(f.p))),saved=restored.relationships.find(x=>x.id===connector.id),savedFlow=restored.relationships.find(x=>x.id===flow.id);assert.equal(saved.targetPropertyPath.length,2);assert.deepEqual(savedFlow.conveyedClassifierIds,[f.signal.id]);assert.equal(savedFlow.documentation,'telemetry');assert.equal(restored.diagrams[0].nodes.find(x=>x.id===b.id).perimeterOffset,.7)});

test('presentation deletion removes nested presentations without deleting semantic properties',()=>{const f=fixture(),outer=createIBDPropertyPresentation(f.p,f.d,f.receiverPart.id),inner=createNestedPropertyPresentation(f.p,f.d,outer,f.ampPart.id);applyOperation(f.p,{type:'remove-presentation',diagramId:f.d.id,nodeId:outer.id});assert.equal(f.d.nodes.some(node=>node.id===inner.id),false);assert(f.p.elements.some(element=>element.id===f.receiverPart.id));assert(f.p.elements.some(element=>element.id===f.ampPart.id))});
