import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {SUPPORTED_TYPE_INVENTORY,SUPPORT_STATES,inventoryEntry} from '../public/src/supported-type-inventory.js';
import {rendererDescriptor} from '../public/src/renderer-registry.js';
import {classifierHeader,propertyNotation,relationshipEndLabels,relationshipNotation,requirementDisplay,traceabilityDirection} from '../public/src/notation-contracts.js';
import {validateBindingEndpoints,validateConstraintProperty} from '../public/src/parametric-notation.js';
import {createProject,defaultElement,normalizeProject} from '../public/src/model.js';
import {applyOperation,canRebaseOperation} from '../public/src/operations.js';
import {DIAGRAMS} from '../public/src/sysml-profile.js';

test('complete inventory entries have every required vertical workflow link',()=>{const complete=SUPPORTED_TYPE_INVENTORY.filter(item=>item.supportStatus==='complete');assert.ok(complete.length>0);for(const item of SUPPORTED_TYPE_INVENTORY)assert.ok(SUPPORT_STATES.includes(item.supportStatus),item.canonicalType);for(const item of complete){assert.ok(item.diagramTypes.length,item.canonicalType);assert.ok(item.paletteAvailability.length||item.creationWorkflow,item.canonicalType);assert.ok(item.rendererKey,item.canonicalType);assert.ok(item.propertySchema,item.canonicalType);assert.ok(item.importMapping,item.canonicalType);assert.equal(item.serialization,'json-project');assert.ok(item.undoRedo);assert.ok(item.testCoverage.length);if(item.creationWorkflow!=='owned-compartment')for(const diagram of item.diagramTypes)assert.equal(rendererDescriptor(item.canonicalType,diagram).supported,true,`${item.canonicalType} / ${diagram}`)}});

test('renderer resolution uses semantic type and context and preserves unknown imported types diagnostically',()=>{const block=rendererDescriptor('Block','Block Definition Diagram'),actor=rendererDescriptor('Actor','Use Case Diagram'),wrong=rendererDescriptor('Actor','Sequence Diagram'),unknown=rendererDescriptor('VendorOpaqueThing','Block Definition Diagram');assert.equal(block.family,'classifier');assert.equal(actor.presentationType,'ActorPresentation');assert.equal(wrong.supported,false);assert.equal(unknown.rendererKey,'diagnostic-presentation');assert.match(unknown.diagnostic,/preserved without conversion/);assert.notEqual(block.presentationType,block.semanticType)});

test('BDD notation retains classifier, property, association-end, and relationship semantics',()=>{const project={elements:[{id:'type',name:'Mass'}]},block={kind:'Block',name:'Vehicle',stereotype:'block',isAbstract:true},property={kind:'ValueProperty',name:'mass',typeRef:'type',multiplicity:'0..1',defaultValue:'10',visibility:'private',isReadOnly:true};assert.deepEqual(classifierHeader(block),{keyword:'block',name:'Vehicle',isAbstract:true});assert.match(propertyNotation(project,property),/^-mass: Mass \[0\.\.1\] = 10 \{readOnly\}$/);assert.deepEqual(relationshipEndLabels({sourceRole:'whole',sourceMultiplicity:'1',targetRole:'part',targetMultiplicity:'*'}),{source:'whole 1',target:'part *'});assert.equal(relationshipNotation('Generalization').marker,'triangle');assert.equal(relationshipNotation('Composition').marker,'diamondFilled');assert.equal(relationshipNotation('Realization').line,'dashed')});

test('IBD and parametric contracts keep structural and binding semantics distinct',()=>{assert.equal(DIAGRAMS['Internal Block Diagram'].relationships.includes('BindingConnector'),false);assert.equal(DIAGRAMS['Parametric Diagram'].relationships.includes('BindingConnector'),true);const project=createProject(),constraintBlock=defaultElement('ConstraintBlock',project.root.id),constraint=defaultElement('ConstraintProperty',project.root.id),value=defaultElement('ValueProperty',project.root.id),parameter=defaultElement('Parameter',constraintBlock.id),block=defaultElement('Block',project.root.id);Object.assign(constraintBlock,{id:'cb'});Object.assign(constraint,{id:'constraint',typeRef:'cb'});Object.assign(value,{id:'value'});Object.assign(parameter,{id:'parameter'});Object.assign(block,{id:'block'});project.elements.push(constraintBlock,constraint,value,parameter,block);assert.equal(validateConstraintProperty(project,constraint).valid,true);constraint.typeRef='block';assert.equal(validateConstraintProperty(project,constraint).valid,false);assert.equal(validateBindingEndpoints(project,'value','parameter').valid,true);assert.equal(validateBindingEndpoints(project,'value','constraint').valid,false);assert.equal(validateBindingEndpoints(project,'value','constraint',{targetPropertyPath:[{propertyId:'parameter'}]}).valid,true)});

test('requirements retain complete display fields and traceability direction contracts',()=>{assert.deepEqual(requirementDisplay({kind:'Requirement',name:'Safe',requirementId:'REQ-1',requirementText:'The system shall stop.'}),{stereotype:'requirement',name:'Safe',requirementId:'REQ-1',text:'The system shall stop.',valid:true});for(const kind of ['Satisfy','Verify','Refine','DeriveReqt','Copy','Trace','Allocate'])assert.ok(traceabilityDirection(kind),kind);assert.deepEqual(traceabilityDirection('Verify'),['test case','requirement'])});

test('lost and found message workflows use explicit anchors, replay, persistence, and no placeholder participant',async()=>{const project=createProject(),interaction=defaultElement('Interaction',project.root.id),lifeline=defaultElement('Lifeline',interaction.id);Object.assign(interaction,{id:'interaction'});Object.assign(lifeline,{id:'lifeline'});project.elements.push(interaction,lifeline);project.diagrams.push({id:'sequence',diagramType:'Sequence Diagram',nodes:[{id:'lifeline-node',elementId:'lifeline',x:100,y:20,width:140,height:45}],edges:[{id:'lost-edge',relationshipId:'lost',sourceNodeId:'lifeline-node',lostAnchor:{x:400,y:180},occurrenceY:180}]});project.relationships.push({id:'lost',kind:'Message',sourceId:'lifeline',targetId:'',messageSort:'lost'});const operation={type:'move-open-message-anchor',diagramId:'sequence',edgeId:'lost-edge',anchorKey:'lostAnchor',anchor:{x:450,y:220},expectedValue:{x:400,y:180}};assert.equal(canRebaseOperation(project,operation),true);applyOperation(project,operation);assert.deepEqual(project.diagrams[0].edges[0].lostAnchor,{x:450,y:220});assert.equal(project.elements.length,2);const loaded=normalizeProject(JSON.parse(JSON.stringify(project)));assert.equal(loaded.relationships[0].targetId,'');assert.deepEqual(loaded.diagrams[0].edges[0].lostAnchor,{x:450,y:220});const app=await readFile(new URL('../public/src/app.js',import.meta.url),'utf8');assert.match(app,/LostMessage','FoundMessage/);assert.match(app,/createOpenMessage/);assert.match(app,/message-open-end/)});

test('palette support labels, diagnostic renderer, and F-01/F-02 shared services remain wired',async()=>{const app=await readFile(new URL('../public/src/app.js',import.meta.url),'utf8');assert.match(app,/support-\$\{support\}/);assert.match(app,/drawDiagnosticPresentation/);assert.match(app,/nodesInSelectionBox/);assert.match(app,/messageGeometry/);assert.equal(inventoryEntry('Actor').supportStatus,'complete');assert.equal(inventoryEntry('Association','relationship').supportStatus,'complete')});
