import test from 'node:test';
import assert from 'node:assert/strict';
import {modelRepositoryElements,isDiagramArtifactElement} from '../public/src/model-repository-visibility.js';
import {diagramRepositoryTree} from '../public/src/diagram-repository-tree.js';
import {routeDiagramRelationships,cleanDiagramLayout,diagramReadabilityIssues} from '../public/src/professional-diagram-layout.js';

const diagramTypes=['Requirement Diagram','Block Definition Diagram','Internal Block Diagram','Use Case Diagram','Activity Diagram','State Machine Diagram','Sequence Diagram','Parametric Diagram','Package Diagram'];
test('packaged diagrams stay out of Model and remain under their owner in Diagrams',()=>{const project={root:{id:'root',kind:'Model',name:'Model'},elements:[{id:'pkg',kind:'Package',name:'Diagram Package',ownerId:'root'},...diagramTypes.map((diagramType,index)=>({id:`artifact-${index}`,kind:diagramType.replaceAll(' ',''),diagramType,name:`Loose ${diagramType}`,ownerId:'pkg'}))],diagrams:diagramTypes.map((diagramType,index)=>({id:`diagram-${index}`,diagramType,name:diagramType,ownerId:'pkg',nodes:[],edges:[]}))};assert.equal(modelRepositoryElements(project).some(item=>isDiagramArtifactElement(item,project.diagrams)),false);assert.deepEqual(modelRepositoryElements(project).map(x=>x.id),['root','pkg']);const tree=diagramRepositoryTree(project),pkg=tree.children.find(x=>x.id==='pkg');assert.equal(pkg.children.filter(x=>x.type==='diagram').length,diagramTypes.length)});
function fixture(){const p={root:{id:'root',kind:'Model'},elements:[{id:'a',kind:'Block'},{id:'b',kind:'Block'},{id:'o1',kind:'Block'},{id:'o2',kind:'Block'}],relationships:[{id:'r',kind:'Dependency',sourceId:'a',targetId:'b'}]},d={id:'d',diagramType:'Block Definition Diagram',nodes:[{id:'a-node',elementId:'a',x:0,y:100,width:60,height:50},{id:'o1-node',elementId:'o1',x:150,y:60,width:100,height:130},{id:'o2-node',elementId:'o2',x:330,y:70,width:100,height:110},{id:'b-node',elementId:'b',x:520,y:100,width:60,height:50}],edges:[{id:'edge',relationshipId:'r',sourceNodeId:'a-node',targetNodeId:'b-node',points:[]} ]};return{p,d}}
test('canonical route and Clean Layout avoid all unrelated expanded node bounds deterministically',()=>{const first=fixture(),second=fixture();assert.equal(routeDiagramRelationships(first.p,first.d).changed,true);assert.equal(routeDiagramRelationships(second.p,second.d).changed,true);assert.deepEqual(first.d.edges[0].points,second.d.edges[0].points);assert.equal(diagramReadabilityIssues(first.p,first.d).some(x=>x.code==='EDGE_THROUGH_NODE'),false);assert.equal(cleanDiagramLayout(first.p,first.d).changed,true);assert.equal(diagramReadabilityIssues(first.p,first.d).some(x=>['NODE_OVERLAP','EDGE_THROUGH_NODE'].includes(x.code)),false)});
test('dense routing has a strict visit bound and preserves a failed diagram atomically',()=>{const {p,d}=fixture(),before=structuredClone(d),result=routeDiagramRelationships(p,d,{maxRouteVisited:0});assert.equal(result.changed,false);assert.deepEqual(d,before)});
test('Route resolves segment overlap with deterministic parallel lanes instead of rejecting',()=>{const first=fixture();first.p.relationships.push({id:'r2',kind:'Dependency',sourceId:'a',targetId:'b'},{id:'r3',kind:'Dependency',sourceId:'a',targetId:'b'});first.d.edges.push({id:'edge-2',relationshipId:'r2',sourceNodeId:'a-node',targetNodeId:'b-node',points:[]},{id:'edge-3',relationshipId:'r3',sourceNodeId:'a-node',targetNodeId:'b-node',points:[]});const result=routeDiagramRelationships(first.p,first.d);assert.equal(result.changed,true,result.reason);assert.doesNotMatch(result.reason||'',/EDGE_SEGMENT_OVERLAP/);assert.equal(diagramReadabilityIssues(first.p,first.d).some(issue=>issue.code==='EDGE_THROUGH_NODE'),false);assert.equal(new Set(first.d.edges.map(edge=>JSON.stringify(edge.points))).size,first.d.edges.length);const routed=structuredClone(first.d.edges.map(edge=>edge.points));assert.equal(routeDiagramRelationships(first.p,first.d).changed,true);assert.deepEqual(first.d.edges.map(edge=>edge.points),routed)});
