import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {applyOperation,deepClone} from '../public/src/operations.js';
import {compareBaselineToCurrent,compareRequirementBaselines,createRequirementBaseline,exportBaseline,saveRequirementBaseline} from '../public/src/requirement-baselines.js';
import {clearSuspectLink,markAffectedLinksSuspect,suspectLinkView} from '../public/src/suspect-links.js';
import {analyzeImpact,buildModelIndexes,impactCsv} from '../public/src/impact-analysis.js';
import {applyImportReconciliation,previewImportReconciliation} from '../public/src/import-reconciliation.js';
import {generateRequirementsReport,serializeRequirementsReport} from '../public/src/requirements-reports.js';

test('Change Control and Reports remains registered after merging the workbench tabs',async()=>{
  const source=await readFile(new URL('../public/src/advanced.js',import.meta.url),'utf8');
  assert.match(source,/import \{compareBaselineToCurrent,createRequirementBaseline\} from '\.\/requirement-baselines\.js';/);
  assert.match(source,/\['changeControl','Change Control & Reports'\]/);
  assert.match(source,/\{structure,behavior,requirements,tables,verification,changeControl,parametrics/);
  assert.doesNotMatch(source,/^(?:<<<<<<<|=======|>>>>>>>)/m);
});

function fixture(){const project=createProject('Change Control'),requirement=defaultElement('Requirement',project.root.id),block=defaultElement('Block',project.root.id),testCase=defaultElement('TestCase',project.root.id);Object.assign(requirement,{id:'req-1',externalId:'EXT-REQ-1',requirementId:'REQ-1',name:'Safe flight',requirementText:'Remain stable',sourceRevision:'A'});Object.assign(block,{id:'block-1',externalId:'EXT-BLOCK-1',name:'Aircraft'});Object.assign(testCase,{id:'test-1',externalId:'EXT-TEST-1',name:'Flight test'});project.elements.push(requirement,block,testCase);project.relationships.push(Object.assign(defaultRelationship('Satisfy',block.id,requirement.id,project.root.id),{id:'rel-satisfy'}),Object.assign(defaultRelationship('Verify',testCase.id,requirement.id,project.root.id),{id:'rel-verify'}));return{project,requirement,block,testCase}}

test('named scoped baselines capture fields and relationships and compare current or another baseline',()=>{const{project,requirement}=fixture(),first=createRequirementBaseline(project,{id:'base-a',name:'A',scope:{requirementIds:[requirement.id]}});saveRequirementBaseline(project,first);requirement.requirementId='REQ-001';requirement.requirementText='Remain stable in all modes';project.relationships.pop();const second=createRequirementBaseline(project,{id:'base-b',name:'B'}),comparison=compareRequirementBaselines(first,second),current=compareBaselineToCurrent(project,first);assert.deepEqual(comparison.summary,{added:0,removed:0,changed:1,relationships:1});assert.deepEqual(comparison.changes[0].fields.sort(),['requirementId','requirementText']);assert.equal(current.summary.changed,1);assert.match(exportBaseline(comparison,'csv'),/relationshipChanges|REQ/)});

test('requirement and related element changes generate clearable suspect links without deleting relationships',()=>{const{project,requirement,block}=fixture();assert.equal(markAffectedLinksSuspect(project,requirement.id,{field:'lifecycleStatus'}).length,0);const records=markAffectedLinksSuspect(project,requirement.id,{field:'requirementText',date:'2026-08-06',reason:'Requirement text changed'});assert.equal(records.length,2);assert.equal(project.relationships.length,2);assert.equal(suspectLinkView(project).length,2);clearSuspectLink(project,records[0].id,{clearedBy:'Reviewer',disposition:'Accepted',clearedDate:'2026-08-07'});assert.equal(suspectLinkView(project).length,1);assert.equal(suspectLinkView(project,{status:'cleared'})[0].clearedBy,'Reviewer');assert.equal(markAffectedLinksSuspect(project,block.id,{field:'name'}).length,1)});

test('impact traversal handles direction, depth, cycles, diagrams, tests and allocations without mutation',()=>{const{project,requirement,block,testCase}=fixture(),back=defaultRelationship('Trace',requirement.id,block.id,project.root.id);back.id='rel-back';project.relationships.push(back);project.diagrams.push({id:'diagram-1',name:'Verification',diagramType:'Requirement Diagram',nodes:[{id:'node-1',elementId:testCase.id}],edges:[]});const before=JSON.stringify(project),result=analyzeImpact(project,requirement.id,{relationshipKinds:['Satisfy','Verify','Trace'],direction:'both',maxDepth:4,indexes:buildModelIndexes(project),validationIssues:[{id:block.id,code:'CHECK'}]});assert.ok(result.cycles.length>0);assert.ok(result.testCases.some(item=>item.element.id===testCase.id));assert.ok(result.diagrams.some(item=>item.id==='diagram-1'));assert.match(impactCsv(result),/Flight test/);assert.equal(JSON.stringify(project),before)});

test('import preview identifies create, update, reuse, conflict and unresolved without root fallback',()=>{const{project}=fixture(),payload={elements:[{id:'incoming-update',externalId:'EXT-REQ-1',kind:'Requirement',requirementId:'REQ-1',requirementText:'Changed',ownerId:project.root.id},{id:'new-1',externalId:'NEW-1',kind:'Requirement',requirementId:'REQ-2',name:'New',ownerId:project.root.id},{id:'bad-1',externalId:'BAD-1',kind:'Requirement',requirementId:'REQ-3',ownerId:'missing'},{id:'reuse-1',externalId:'EXT-BLOCK-1',kind:'Block',name:'Aircraft',ownerId:project.root.id},{id:'conflict-1',externalId:'EXT-REQ-1',kind:'Requirement',requirementId:'DIFFERENT',ownerId:project.root.id}],relationships:[]},preview=previewImportReconciliation(project,payload);assert.equal(preview.summary.Update,1);assert.equal(preview.summary.Create,1);assert.equal(preview.summary.Unresolved,1);assert.equal(preview.summary.Reuse,1);assert.equal(preview.summary.Conflict,1)});

test('reimport updates without duplication, preserves relationships and geometry, and marks links suspect',()=>{const{project}=fixture();project.diagrams.push({id:'d1',nodes:[{id:'n1',elementId:'req-1',x:90,y:120}],edges:[]});const payload={elements:[{id:'import-req',externalId:'EXT-REQ-1',kind:'Requirement',requirementId:'REQ-1',requirementText:'Changed on import',ownerId:project.root.id}],relationships:[]},preview=previewImportReconciliation(project,payload),result=applyImportReconciliation(project,preview);assert.equal(result.applied,true);assert.equal(project.elements.filter(e=>e.kind==='Requirement').length,1);assert.equal(project.relationships.length,2);assert.equal(project.diagrams[0].nodes[0].x,90);assert.equal(project.suspectLinks.length,2);const again=applyImportReconciliation(project,previewImportReconciliation(project,payload));assert.equal(again.applied,true);assert.equal(project.elements.filter(e=>e.kind==='Requirement').length,1)});


test('reconciliation resolves incoming owner chains independent of row order',()=>{const{project}=fixture(),payload={elements:[{id:'child',externalId:'CHILD',kind:'Requirement',requirementId:'REQ-C',ownerId:'parent'},{id:'parent',externalId:'PARENT',kind:'Package',ownerId:project.root.id}],relationships:[]},preview=previewImportReconciliation(project,payload),result=applyImportReconciliation(project,preview);assert.equal(result.applied,true);assert.equal(project.elements.find(item=>item.id==='child').ownerId,'parent')});
test('failed reconciliation rolls the transaction back',()=>{const{project}=fixture(),before=JSON.stringify(project),preview=previewImportReconciliation(project,{elements:[{id:'bad',externalId:'BAD',kind:'Requirement',ownerId:'missing'}],relationships:[]}),result=applyImportReconciliation(project,preview);assert.equal(result.applied,false);assert.equal(JSON.stringify(project),before)});

test('reports serialize as CSV, XLSX, JSON and printable HTML',()=>{const{project}=fixture();markAffectedLinksSuspect(project,'req-1',{field:'requirementText'});for(const type of ['requirement-specification','satisfy-matrix','verification-plan','coverage','suspect-links']){const report=generateRequirementsReport(project,{type});assert.ok(report.columns.length);assert.match(serializeRequirementsReport(report,'csv'),/^"/);assert.doesNotThrow(()=>JSON.parse(serializeRequirementsReport(report,'json')));assert.match(serializeRequirementsReport(report,'html'),/<!doctype html>/);assert.equal(serializeRequirementsReport(report,'xlsx').SheetNames[0],'Report')}});

test('baseline, suspect, import decision, and saved report operations replay through collaboration and persist',()=>{const{project}=fixture(),baseline=createRequirementBaseline(project,{id:'replay-base'}),report={id:'report-1',name:'Coverage',type:'coverage'};applyOperation(project,{type:'create-requirement-baseline',baseline});applyOperation(project,{type:'mark-suspect-link',relationshipId:'rel-satisfy',record:{id:'suspect-replay',reason:'Replay',date:'2026-08-06'}});applyOperation(project,{type:'clear-suspect-link',suspectId:'suspect-replay',clearance:{clearedBy:'Lead',disposition:'Accepted',clearedDate:'2026-08-07'}});applyOperation(project,{type:'record-import-decision',decision:{id:'decision-1',status:'Reuse'}});applyOperation(project,{type:'save-report',report});const restored=normalizeProject(deepClone(project));assert.equal(restored.requirementBaselines[0].id,'replay-base');assert.equal(restored.suspectLinks[0].clearedBy,'Lead');assert.equal(restored.importHistory[0].status,'Reuse');assert.equal(restored.savedReports[0].id,'report-1');assert.throws(()=>applyOperation(restored,{type:'delete-requirement-baseline',baselineId:'replay-base'}),/confirmation/)});

test('indexed impact traversal scales to thousands of requirements and relationships',()=>{const project=createProject('Large');for(let index=0;index<3000;index++){const requirement=defaultElement('Requirement',project.root.id);requirement.id=`r-${index}`;requirement.requirementId=`REQ-${index}`;project.elements.push(requirement);if(index){const relationship=defaultRelationship('DeriveReqt',`r-${index-1}`,requirement.id,project.root.id);relationship.id=`link-${index}`;project.relationships.push(relationship)}}const indexes=buildModelIndexes(project),result=analyzeImpact(project,'r-0',{relationshipKinds:['DeriveReqt'],direction:'outgoing',maxDepth:3000,indexes});assert.equal(indexes.requirementIds.size,3000);assert.equal(result.impacted.length,2999)});
