import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createProject,defaultElement,normalizeProject,qualifiedName} from '../public/src/model.js';
import {removePresentation,showElementOnDiagram,showRelationshipOnDiagram} from '../public/src/diagram-presentations.js';
import {addRequirementDecomposition,createRequirement,createRequirementRelationship,getDerivedRequirements,getGeneralTraces,getRefiningElements,getRequirementAncestors,getRequirementChildren,getSatisfyingElements,getVerifyingElements,validateRequirementRelationship} from '../public/src/requirement-architecture.js';
import {validate} from '../public/src/validator.js';

function fixture(){const project=createProject('Requirements'),requirement=createRequirement(project,{id:'req-main',externalId:'EXT-REQ-MAIN',requirementId:'REQ-001',name:'Safe tire',shortTitle:'Tire safety',requirementText:'The installed tire shall retain pressure.',ownerId:project.root.id}),block=Object.assign(defaultElement('Block',project.root.id),{id:'block',name:'Wheel'}),testCase=Object.assign(defaultElement('TestCase',project.root.id),{id:'test',name:'Pressure test'}),activity=Object.assign(defaultElement('Activity',project.root.id),{id:'activity',name:'Inflate'});project.elements.push(block,testCase,activity);return{project,requirement,block,testCase,activity}}
test('Requirement identity, complete text, qualified name, presentations, and JSON persistence remain separate',()=>{const{project,requirement}=fixture(),a={id:'d-a',name:'A',diagramType:'Requirement Diagram',ownerId:project.root.id,contextId:project.root.id,nodes:[],edges:[]},b={...a,id:'d-b',name:'B',nodes:[],edges:[]};project.diagrams.push(a,b);const pa=showElementOnDiagram(project,requirement.id,a.id).node,pb=showElementOnDiagram(project,requirement.id,b.id).node;assert.notEqual(pa.id,pb.id);assert.equal(project.elements.filter(item=>item.id===requirement.id).length,1);removePresentation(project,a.id,pa.id);assert.ok(project.elements.includes(requirement));assert.equal(b.nodes.length,1);const restored=normalizeProject(JSON.parse(JSON.stringify(project))),saved=restored.elements.find(item=>item.id===requirement.id);assert.equal(saved.externalId,'EXT-REQ-MAIN');assert.equal(saved.requirementId,'REQ-001');assert.equal(saved.requirementText,requirement.requirementText);assert.match(qualifiedName(restored,saved.id),/REQ|Safe tire/)});
test('controlled decomposition is distinct from deriveReqt and rejects cycles',()=>{const{project,requirement}=fixture(),child=createRequirement(project,{id:'req-child',externalId:'EXT-CHILD',requirementId:'REQ-001.1',name:'Pressure retention',requirementText:'Retain pressure for one hour.'});addRequirementDecomposition(project,requirement.id,child.id);assert.deepEqual(getRequirementChildren(project,requirement.id).map(item=>item.requirement.id),[child.id]);assert.deepEqual(getRequirementAncestors(project,child.id).map(item=>item.requirement.id),[requirement.id]);const derive=createRequirementRelationship(project,'DeriveReqt',child.id,requirement.id,{id:'derive'});assert.equal(child.ownerId,requirement.id);assert.equal(derive.kind,'DeriveReqt');assert.throws(()=>addRequirementDecomposition(project,child.id,requirement.id),/cycle/)});
test('typed relationship direction and meaning remain distinct and never grant verification credit',()=>{const{project,requirement,block,testCase,activity}=fixture(),source=createRequirement(project,{id:'req-source',externalId:'EXT-SOURCE',requirementId:'REQ-S',name:'Source',requirementText:'Source requirement.'});const relationships=[createRequirementRelationship(project,'DeriveReqt',requirement.id,source.id,{id:'derive'}),createRequirementRelationship(project,'Satisfy',block.id,requirement.id,{id:'satisfy'}),createRequirementRelationship(project,'Verify',testCase.id,requirement.id,{id:'verify'}),createRequirementRelationship(project,'Refine',activity.id,requirement.id,{id:'refine'}),createRequirementRelationship(project,'Trace',requirement.id,block.id,{id:'trace'}),createRequirementRelationship(project,'Copy',requirement.id,source.id,{id:'copy'}),createRequirementRelationship(project,'Allocate',requirement.id,block.id,{id:'allocate',allocationKind:'requirement'})];assert.match(validateRequirementRelationship(project,'Satisfy',requirement.id,block.id).reason,/direction|start/);assert.match(validateRequirementRelationship(project,'Verify',block.id,requirement.id).reason,/direction/);assert.equal(getDerivedRequirements(project,source.id)[0].relationship.id,'derive');assert.equal(getSatisfyingElements(project,requirement.id)[0].element.id,block.id);assert.equal(getVerifyingElements(project,requirement.id)[0].verificationCredit,false);assert.equal(getRefiningElements(project,requirement.id)[0].element.id,activity.id);assert.equal(getGeneralTraces(project,requirement.id)[0].reasonCode,'GENERAL_TRACE_ONLY');assert.equal(requirement.verificationStatus,'Not Planned');assert.equal(relationships.length,7)});
test('deleting a relationship presentation does not delete the semantic relationship',()=>{const{project,requirement,block}=fixture(),relationship=createRequirementRelationship(project,'Satisfy',block.id,requirement.id,{id:'satisfy'}),diagram={id:'diagram',name:'Req',diagramType:'Requirement Diagram',ownerId:project.root.id,contextId:project.root.id,nodes:[],edges:[]};project.diagrams.push(diagram);showElementOnDiagram(project,block.id,diagram.id);showElementOnDiagram(project,requirement.id,diagram.id);assert.equal(showRelationshipOnDiagram(project,relationship.id,diagram.id).valid,true);diagram.edges=[];assert.equal(project.relationships.find(item=>item.id===relationship.id),relationship)});
test('validation flags missing identity/text and reversed relationships without weakening severity',()=>{const{project,requirement,block}=fixture();requirement.requirementText='';project.relationships.push({...createRequirementRelationship(project,'Trace',requirement.id,block.id,{id:'bad'}),kind:'Satisfy',sourceId:requirement.id,targetId:block.id});const issues=validate(project);assert.ok(issues.some(item=>item.code==='REQUIREMENT_TEXT_REQUIRED'&&item.severity==='error'));assert.ok(issues.some(item=>item.code==='SATISFY_ENDPOINT_INVALID'&&item.severity==='error'))});
test('Requirement workbench commits complete text and External ID on blur without rerendering ordinary keystrokes',()=>{const source=fs.readFileSync(new URL('../public/src/advanced.js',import.meta.url),'utf8');assert.match(source,/contenteditable data-field="requirementText"/);assert.match(source,/contenteditable data-field="externalId"/);assert.match(source,/\[contenteditable\]\[data-field\].*onblur/);assert.doesNotMatch(source,/\[contenteditable\]\[data-field\].*oninput/)});
