import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,defaultElement,normalizeProject} from '../public/src/model.js';
import {applyOperation,deepClone} from '../public/src/operations.js';
import {editRequirementCells,normalizeRequirementTable,requirementTableRows,saveRequirementTable,visibleTableWindow} from '../public/src/requirements-table.js';
import {createMatrixRelationship,deleteMatrixRelationship,matrixAxes,matrixCell,matrixDefinition,relationshipIndex,validMatrixCell,visibleMatrixWindow} from '../public/src/relationship-matrix.js';
import {assignTestCase,createTestCase,createVerificationExecution,verificationCoverage} from '../public/src/verification-model.js';
import {verificationPlan} from '../public/src/verification-plan.js';

function fixture(){const project=createProject('Phase 3');const requirement=defaultElement('Requirement',project.root.id);Object.assign(requirement,{name:'Flight safety',requirementId:'REQ-1',priority:'High'});const block=defaultElement('Block',project.root.id);block.name='Aircraft';project.elements.push(requirement,block);return{project,requirement,block}}

test('table definitions persist and rows support filtering, sorting, inline and safe batch editing',()=>{const{project,requirement}=fixture(),table=saveRequirementTable(project,normalizeRequirementTable({name:'Safety',filters:[{key:'priority',operator:'equals',value:'High'}],sort:[{key:'name',direction:'asc'}]}));normalizeProject(project);assert.equal(project.requirementTables[0].name,'Safety');assert.deepEqual(requirementTableRows(project,table).map(row=>row.id),[requirement.id]);const replay=deepClone(project),operation=editRequirementCells(project,[{id:requirement.id,field:'requirementText',value:'The aircraft shall be safe.'}]);assert.match(requirement.requirementText,/safe/);assert.throws(()=>editRequirementCells(project,[{id:requirement.id,field:'id',value:'changed'}]),/not editable/);applyOperation(replay,operation);assert.match(replay.elements[0].requirementText,/safe/)});

test('shared matrix creates and deletes semantic relationships and rejects invalid cells',()=>{const{project,requirement,block}=fixture(),definition=matrixDefinition('satisfy'),axes=matrixAxes(project,definition);assert.equal(axes.rows[0].id,requirement.id);assert.equal(validMatrixCell(definition,requirement,block),true);const{relationship}=createMatrixRelationship(project,definition,requirement,block);assert.equal(matrixCell(project,definition,requirement,block,relationshipIndex(project)).populated,true);assert.equal(relationship.sourceId,block.id);assert.throws(()=>createMatrixRelationship(project,definition,requirement,block),/already exists/);assert.throws(()=>deleteMatrixRelationship(project,relationship.id),/confirmation/);deleteMatrixRelationship(project,relationship.id,{confirmed:true});assert.equal(project.relationships.length,0);assert.equal(validMatrixCell(definition,requirement,requirement),false)});

test('Test Cases persist separately from multiple Verification Executions and update coverage',()=>{const{project,requirement}=fixture(),testCase=createTestCase(project,{name:'Flight test',procedure:'Fly profile',expectedResult:'No unsafe state'});assignTestCase(project,testCase.id,requirement.id);createVerificationExecution(project,testCase.id,{id:'run-1',executionDate:'2026-08-01',verdict:'Fail',actualResult:'Instability'});createVerificationExecution(project,testCase.id,{id:'run-2',executionDate:'2026-08-02',verdict:'Pass',actualResult:'Stable',configuration:'Aircraft A'});const restored=normalizeProject(deepClone(project)),coverage=verificationCoverage(restored),plan=verificationPlan(restored);assert.equal(restored.verificationExecutions.length,2);assert.deepEqual({assigned:coverage.assigned,executed:coverage.executed,passed:coverage.passed,failed:coverage.failed,notRun:coverage.notRun},{assigned:1,executed:1,passed:1,failed:0,notRun:0});assert.equal(plan[0].latestExecution.id,'run-2');assert.equal(plan[0].status,'Executed')});

test('verification execution collaboration operations replay and can be undone',()=>{const{project,requirement}=fixture(),testCase=createTestCase(project,{name:'Replay case'});assignTestCase(project,testCase.id,requirement.id);const before=deepClone(project),execution=createVerificationExecution(project,testCase.id,{id:'replay-run',verdict:'Blocked'}),operation={type:'create-verification-execution',execution};const replay=deepClone(before);applyOperation(replay,operation);assert.equal(replay.verificationExecutions[0].verdict,'Blocked');applyOperation(replay,{type:'delete-verification-execution',executionId:execution.id});assert.equal(replay.verificationExecutions.length,0)});

test('large table and matrix windows virtualize rather than returning every cell',()=>{const rows=Array.from({length:10_000},(_,id)=>({id})),columns=Array.from({length:2_000},(_,id)=>({id}));const table=visibleTableWindow(rows,50_000,600);const matrix=visibleMatrixWindow(rows,columns,{scrollTop:50_000,scrollLeft:20_000,width:1000,height:600});assert.ok(table.rows.length<40);assert.ok(matrix.rows.length<40);assert.ok(matrix.columns.length<20);assert.equal(matrix.totalHeight,320_000);assert.equal(matrix.totalWidth,240_000)});
