import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject} from '../public/src/model.js';
import {createConfiguration,createDefinition,createInstance,createSiteContext,createUsage} from '../public/src/semantic-foundation.js';
import {applyOperation} from '../public/src/operations.js';
import {createCollaborationOperation,validateCollaborationOperation} from '../public/src/collaboration-operation.js';

test('foundation operations serialize and replay through collaboration envelopes',()=>{const project=createProject('Operations'),definition=createDefinition(project,'Block',{id:'definition',name:'Tire'}),site=createSiteContext(project,{id:'site',name:'Site'}),usage=createUsage(project,'PartProperty',{id:'usage',name:'tire',ownerId:site.id}),instance=createInstance(project,{id:'instance',name:'unit',definitionId:definition.id}),configuration=createConfiguration(project,{id:'configuration',name:'As built'});const operations=[{type:'assign-usage-definition',usageId:usage.id,definitionId:definition.id},{type:'assign-instance-usage',instanceId:instance.id,usageId:usage.id},{type:'add-configuration-item',configurationId:configuration.id,item:{id:'item',targetType:'Instance',targetId:instance.id}},{type:'assign-requirement-applicability',requirementId:'missing',rule:{targetType:'Instance',targetId:instance.id}}];applyOperation(project,operations[0]);applyOperation(project,operations[1]);applyOperation(project,operations[2]);assert.equal(project.elements.find(item=>item.id==='instance').fulfilledUsageId,'usage');assert.equal(project.elements.find(item=>item.id==='configuration').items.length,1);for(const operation of operations){const envelope=createCollaborationOperation(operation,{projectId:project.id,branchId:'site-a',clientId:'client',timestamp:'2026-01-01T00:00:00.000Z'});assert.equal(validateCollaborationOperation(envelope).ok,true);assert.equal(JSON.parse(JSON.stringify(envelope)).operation.type,operation.type)}});
test('configuration item replay is idempotent by stable item ID and branches remain envelope-isolated',()=>{const project=createProject(),definition=createDefinition(project,'Block',{id:'configured-definition'}),configuration=createConfiguration(project,{id:'configuration',name:'Working'}),operation={type:'add-configuration-item',configurationId:configuration.id,item:{id:'stable-item',targetType:'Definition',targetId:definition.id}};applyOperation(project,operation);applyOperation(project,operation);assert.equal(configuration.items.length,1);const a=createCollaborationOperation(operation,{projectId:project.id,branchId:'a',clientId:'a'}),b=createCollaborationOperation(operation,{projectId:project.id,branchId:'b',clientId:'b'});assert.notEqual(a.branchId,b.branchId);assert.deepEqual(a.operation,b.operation)});
