import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {semanticThreeWayMerge} from '../public/src/semantic-merge.js';
import {COMMENT_TARGETS,REVIEW_STATUSES,createModelComment,createReviewRequest,transitionReview} from '../public/src/model-reviews.js';
import {applyOperation} from '../public/src/operations.js';

const clone=value=>structuredClone(value);
function fixture(){const base=createProject('Merge');const block=defaultElement('Block',base.root.id);block.id='block-stable';block.name='Receiver';block.documentation='Base docs';base.elements.push(block);const diagram={id:'diagram-stable',externalId:'diagram-stable',name:'BDD',diagramType:'Block Definition Diagram',ownerId:base.root.id,nodes:[],edges:[]};base.diagrams.push(diagram);diagram.nodes.push({id:'node-stable',elementId:block.id,x:10,y:10,width:100,height:70});return normalizeProject(base)}

test('three-way merge auto-merges independent fields, additions, relationships, and geometry',()=>{const base=fixture(),source=clone(base),target=clone(base);source.elements[0].documentation='Source docs';target.elements[0].name='Target Receiver';source.elements.push({...defaultElement('Port','block-stable'),id:'port-source',name:'Input'});target.elements.push({...defaultElement('Block',base.root.id),id:'block-target',name:'Display'});source.relationships.push({...defaultRelationship('Trace','block-stable','block-target',base.root.id),id:'trace-source'});source.diagrams[0].nodes[0].x=50;target.diagrams[0].nodes[0].height=120;const result=semanticThreeWayMerge(base,source,target);assert.equal(result.canMerge,true);assert.equal(result.project.elements.find(x=>x.id==='block-stable').documentation,'Source docs');assert.equal(result.project.elements.find(x=>x.id==='block-stable').name,'Target Receiver');assert.equal(result.project.diagrams[0].nodes[0].x,50);assert.equal(result.project.diagrams[0].nodes[0].height,120);assert.ok(result.project.elements.some(x=>x.id==='port-source'));assert.ok(result.project.relationships.some(x=>x.id==='trace-source'))});

test('three-way merge requires review for semantic conflict classes',()=>{const scenarios=[['same-property',(s,t)=>{s.elements[0].name='A';t.elements[0].name='B'}],['move-move',(s,t)=>{s.elements[0].ownerId='package-a';t.elements[0].ownerId='package-b'}],['delete-edit',(s,t)=>{s.elements=[];t.elements[0].name='Edited'}],['endpoint-conflict',(s,t,b)=>{const r={...defaultRelationship('Connector','block-stable','x',b.root.id),id:'connector-stable'};b.relationships.push(clone(r));s.relationships.push({...r,sourceId:'a'});t.relationships.push({...r,sourceId:'b'})}],['id-collision',(s,t,b)=>{s.elements.push({...defaultElement('Block',b.root.id),id:'collision',name:'A'});t.elements.push({...defaultElement('Block',b.root.id),id:'collision',name:'B'})}],['import-conflict',(s,t)=>{s.elements[0].externalId='IMPORT-A';t.elements[0].externalId='IMPORT-B'}]];for(const [expected,change] of scenarios){const base=fixture(),source=clone(base),target=clone(base);change(source,target,base);const result=semanticThreeWayMerge(base,source,target);assert.ok(result.conflicts.some(item=>item.type===expected),expected)}});

test('comments attach to supported SysML targets and reviews follow governed statuses',()=>{const project=fixture();assert.deepEqual(COMMENT_TARGETS,['Block','Requirement','Port','Connector','Diagram','Relationship','State','Activity','ParametricElement','ValidationIssue']);assert.deepEqual(REVIEW_STATUSES,['Draft','Open','Changes Requested','Approved','Rejected','Merged']);const comment=createModelComment(project,{commentId:'comment-1',targetType:'Block',targetId:'block-stable',body:'Please review with @alex',author:'Ryan'});assert.deepEqual(comment.mentions,['alex']);const review=createReviewRequest(project,{reviewId:'review-1',sourceBranchId:'feature',targetBranchId:'main',title:'Receiver review',author:'Ryan'});transitionReview(project,review.reviewId,'Open','Ryan');assert.equal(review.status,'Open');const replay=applyOperation(fixture(),{type:'create-comment',comment:{commentId:'comment-1',threadId:'thread-1',targetType:'Block',targetId:'block-stable',body:'Review',author:'Ryan',createdAt:'2026-01-01'}});assert.equal(replay.comments[0].commentId,'comment-1')});
