import test from 'node:test';
import assert from 'node:assert/strict';
import {lifelineGeometry,messageGeometry,messagePathData,moveMessageOccurrence,reconnectMessage,resizeLifelineTimeline,sequenceLifelineAt} from '../public/src/sequence-interactions.js';
import {applyOperation} from '../public/src/operations.js';

const fixture=()=>({elements:[{id:'a',kind:'Lifeline'},{id:'b',kind:'Lifeline'},{id:'c',kind:'Lifeline'}],relationships:[{id:'m',kind:'Message',sourceId:'a',targetId:'b',messageSort:'synchronous'}],diagrams:[{id:'d',diagramType:'Sequence Diagram',nodes:[{id:'na',elementId:'a',x:100,y:40,width:120,height:500},{id:'nb',elementId:'b',x:400,y:40,width:120,height:500},{id:'nc',elementId:'c',x:700,y:40,width:120,height:500}],edges:[{id:'em',relationshipId:'m',sourceNodeId:'na',targetNodeId:'nb',occurrenceY:180}]}]});

test('messages derive endpoints from Lifelines, move vertically, and support self loops',()=>{const project=fixture(),diagram=project.diagrams[0],edge=diagram.edges[0],message=project.relationships[0];assert.deepEqual(messageGeometry(diagram,edge,message).path,[{x:160,y:180},{x:460,y:180}]);diagram.nodes[0].x=200;assert.equal(messageGeometry(diagram,edge,message).path[0].x,260);moveMessageOccurrence(edge,260);assert.equal(messageGeometry(diagram,edge,message).y,260);edge.targetNodeId='na';message.targetId='a';const self=messageGeometry(diagram,edge,message);assert.equal(self.self,true);assert.equal(messagePathData(self),'M260 260 L314 260 L314 294 L260 294')});
test('Lifeline timeline resizing is independent of its head and has a minimum',()=>{const node={x:10,y:20,width:100,height:200,headHeight:45};resizeLifelineTimeline(node,40);assert.equal(node.timelineEndY,145);assert.equal(lifelineGeometry(node).headHeight,45);resizeLifelineTimeline(node,600);assert.equal(lifelineGeometry(node).timelineEndY,600)});
test('message reconnection only accepts Lifeline presentations',()=>{const project=fixture(),diagram=project.diagrams[0],edge=diagram.edges[0],message=project.relationships[0];assert.equal(sequenceLifelineAt(project,diagram,{x:760,y:200})?.id,'nc');assert.equal(reconnectMessage(diagram,project,edge,message,'target',diagram.nodes[2]),true);assert.equal(message.targetId,'c');project.elements.push({id:'block',kind:'Block'});assert.equal(reconnectMessage(diagram,project,edge,message,'target',{id:'bad',elementId:'block'}),false)});
test('granular sequence operations replay and validate endpoints',()=>{let project=fixture();project=applyOperation(project,{type:'move-message-occurrence',diagramId:'d',edgeId:'em',occurrenceY:330});project=applyOperation(project,{type:'resize-lifeline-timeline',diagramId:'d',nodeId:'na',timelineEndY:720});project=applyOperation(project,{type:'reconnect-message',diagramId:'d',edgeId:'em',relationshipId:'m',end:'target',nodeId:'nc',elementId:'c'});assert.equal(project.diagrams[0].edges[0].occurrenceY,330);assert.equal(project.diagrams[0].nodes[0].timelineEndY,720);assert.equal(project.relationships[0].targetId,'c')});
