import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createProject,defaultElement,defaultRelationship,normalizeProject} from '../public/src/model.js';
import {validateBehaviorConnection,initializeBehaviorRelationship} from '../public/src/behavior-model.js';
import {USE_CASE_MANIFEST,validateUseCaseManifest} from '../public/src/use-case-manifest.js';
import {inventoryEntry} from '../public/src/supported-type-inventory.js';
import {showElementOnDiagram} from '../public/src/diagram-presentations.js';

const add=(project,kind,id,ownerId=project.root.id)=>{const element=Object.assign(defaultElement(kind,ownerId),{id,name:id});project.elements.push(element);return element};
test('authoritative Use Case coverage includes every palette item and owned ExtensionPoint',()=>{assert.equal(validateUseCaseManifest(),true);for(const kind of ['Actor','UseCase','Block','Package','Comment','Association','Generalization','Include','Extend','Dependency','Trace','Refine'])assert.ok(USE_CASE_MANIFEST.some(item=>item.canonicalType===kind&&item.paletteRequired),kind);assert.equal(USE_CASE_MANIFEST.find(item=>item.canonicalType==='ExtensionPoint').paletteRequired,false);assert.equal(inventoryEntry('Actor').supportStatus,'complete');assert.equal(inventoryEntry('UseCase').supportStatus,'complete')});
test('Actor and UseCase semantics remain separate from reusable presentations',()=>{const project=createProject('Use Cases'),actor=add(project,'Actor','actor'),useCase=add(project,'UseCase','use-case'),diagram={id:'ucd',diagramType:'Use Case Diagram',ownerId:project.root.id,contextId:project.root.id,nodes:[],edges:[]};project.diagrams.push(diagram);const first=showElementOnDiagram(project,actor.id,diagram.id,{x:10,y:20}),second={...first.node,id:'actor-presentation-two',x:300};diagram.nodes.push(second);showElementOnDiagram(project,useCase.id,diagram.id,{x:160,y:100});const loaded=normalizeProject(JSON.parse(JSON.stringify(project)));assert.equal(loaded.elements.filter(item=>item.id===actor.id).length,1);assert.equal(loaded.diagrams[0].nodes.filter(item=>item.elementId===actor.id).length,2);assert.equal(actor.metaclass,'Actor');assert.equal(useCase.metaclass,'UseCase')});
test('Use Case relationship validation preserves UML endpoint rules and direction',()=>{const project=createProject(),actor=add(project,'Actor','actor'),actor2=add(project,'Actor','actor-2'),a=add(project,'UseCase','a'),b=add(project,'UseCase','b');assert.equal(validateBehaviorConnection(project,'Include',a.id,b.id).valid,true);assert.equal(validateBehaviorConnection(project,'Include',actor.id,a.id).valid,false);assert.equal(validateBehaviorConnection(project,'Generalization',actor2.id,actor.id).valid,true);assert.equal(validateBehaviorConnection(project,'Generalization',actor.id,a.id).valid,false);project.relationships.push(defaultRelationship('Generalization',actor.id,actor2.id,project.root.id));assert.match(validateBehaviorConnection(project,'Generalization',actor2.id,actor.id).message,/cycle/);const include=initializeBehaviorRelationship(defaultRelationship('Include',a.id,b.id,project.root.id)),extend=initializeBehaviorRelationship(defaultRelationship('Extend',a.id,b.id,project.root.id));assert.equal(include.stereotype,'include');assert.equal(extend.stereotype,'extend');assert.equal(include.direction,'sourceToTarget');assert.equal(extend.direction,'sourceToTarget')});
test('production app exposes Actor notation, subject boundary, guided extension points, and atomic endpoint validation',async()=>{const app=await readFile(new URL('../public/src/app.js',import.meta.url),'utf8');for(const token of ["e.kind==='Actor'","drawActor(g,e,w)","drawUseCaseSubject","+ Extension Point","guidedReferenceField('Extension point'","Use Case communication Association must connect one Actor and one Use Case"])assert.ok(app.includes(token),token);assert.ok(!app.includes("prompt('Extension point"))});
