import test from 'node:test';
import assert from 'node:assert/strict';
import {applyWorkspace,breadcrumb,closeTab,defaultWorkbenchState,mixedValue,normalizeWorkbenchState,openTab,reopenTab,reorderTab,resizePanel,searchRepository,toggleFavorite,togglePanel} from '../public/src/workbench-state.js';
import {CommandRegistry} from '../public/src/command-registry.js';

const project={id:'p',name:'Model',root:{id:'root',name:'Model'},activeDiagramId:'d1',elements:[{id:'pkg',name:'Structure',qualifiedName:'Model::Structure',kind:'Package',ownerId:'root'},{id:'block',name:'Receiver',qualifiedName:'Model::Structure::Receiver',externalId:'EXT-1',kind:'Block',ownerId:'pkg',documentation:'radio subsystem'}],diagrams:[{id:'d1',name:'BDD',diagramType:'Block Definition Diagram',ownerId:'pkg'},{id:'d2',name:'IBD',diagramType:'Internal Block Diagram',ownerId:'pkg'}]};

test('default layout and workspace switching preserve document state',()=>{let state=defaultWorkbenchState(project);assert.equal(state.workspace,'Modeling');assert.equal(state.panels.explorer,true);state=openTab(state,{id:'d2',type:'diagram'});state=applyWorkspace(state,'Validation');assert.equal(state.sizes.bottom,300);assert.deepEqual(state.openTabs.map(t=>t.id),['d1','d2'])});
test('panel size and visibility persist through normalization',()=>{let state=resizePanel(defaultWorkbenchState(project),'left',999);assert.equal(state.sizes.left,520);state=togglePanel(state,'properties',false);const restored=normalizeWorkbenchState(JSON.parse(JSON.stringify(state)),project);assert.equal(restored.panels.properties,false);assert.equal(restored.sizes.left,520)});
test('tabs avoid duplicates, reorder, close, and reopen without deleting diagrams',()=>{let state=defaultWorkbenchState(project);state=openTab(openTab(state,{id:'d2',type:'diagram'}),{id:'d2',type:'diagram'});assert.equal(state.openTabs.length,2);state=reorderTab(state,'d2',0);assert.equal(state.openTabs[0].id,'d2');state=closeTab(state,'d2');assert.equal(project.diagrams.length,2);state=reopenTab(state);assert(state.openTabs.some(t=>t.id==='d2'))});
test('stale tabs and favorites are removed during project switching',()=>{const state={...defaultWorkbenchState(project),openTabs:[{id:'missing',type:'diagram'}],activeTabId:'missing',favorites:['missing','block']},restored=normalizeWorkbenchState(state,project);assert.deepEqual(restored.openTabs,[{id:'d1',type:'diagram'}]);assert.deepEqual(restored.favorites,['block'])});
test('breadcrumbs rebuild after rename and repository search covers semantic fields',()=>{assert.deepEqual(breadcrumb(project,'d1').map(item=>item.label),['Model','Structure','BDD']);project.elements[0].name='Architecture';assert.deepEqual(breadcrumb(project,'d1').map(item=>item.label),['Model','Architecture','BDD']);assert.equal(searchRepository(project,'radio')[0].id,'block');assert.equal(searchRepository(project,'ext-1')[0].id,'block')});
test('favorites and mixed multi-selection values are safe',()=>{let state=toggleFavorite(defaultWorkbenchState(project),'block');assert.deepEqual(state.favorites,['block']);state=toggleFavorite(state,'block');assert.deepEqual(state.favorites,[]);assert.equal(mixedValue([{kind:'Block'},{kind:'Block'}],'kind'),'Block');assert.equal(mixedValue([{name:'A'},{name:'B'}],'name'),null)});
test('command registry rejects duplicate IDs and searches enabled commands',()=>{const registry=new CommandRegistry(),events=[];registry.register({id:'model.block',label:'Create Block',category:'Model',shortcut:'Ctrl+B',execute:()=>events.push('block')});assert.throws(()=>registry.register({id:'model.block',label:'Duplicate',execute(){}}),/Duplicate/);assert.equal(registry.search('create block').length,1);assert.equal(registry.execute('model.block'),true);assert.deepEqual(events,['block'])});
