import {test,expect} from './fixtures.mjs';

async function open(page){await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Activity UI'),root=p.root.id;const elements=[
{id:'activity',externalId:'ACT',kind:'Activity',metaclass:'Activity',name:'Process',ownerId:root},
{id:'region',externalId:'REG',kind:'InterruptibleActivityRegion',metaclass:'InterruptibleActivityRegion',name:'Abortable',ownerId:'activity',memberIds:['inside']},
{id:'inside',externalId:'IN',kind:'Action',metaclass:'Action',name:'Inside',ownerId:'region'},
{id:'outside',externalId:'OUT',kind:'Action',metaclass:'Action',name:'Outside',ownerId:'activity'},
{id:'outside2',externalId:'OUT2',kind:'Action',metaclass:'Action',name:'Outside 2',ownerId:'activity'}];p.elements.push(...elements);p.relationships.push({id:'interrupt',externalId:'INT',name:'abort',kind:'InterruptingEdge',metaclass:'ActivityEdge',stereotype:'',sourceId:'inside',targetId:'outside',ownerId:'activity',guard:'abortRequested',weight:'2',direction:'sourceToTarget',documentation:'',createdAt:new Date().toISOString(),modifiedAt:new Date().toISOString()});const activityDiagram={id:'diagram',name:'Process Activity',diagramType:'Activity Diagram',ownerId:root,contextId:'activity',headerText:'',nodes:[{id:'nr',elementId:'region',x:120,y:120,width:360,height:250},{id:'ni',elementId:'inside',x:190,y:210,width:190,height:110,parentPresentationId:'nr'},{id:'no',elementId:'outside',x:650,y:210,width:190,height:110},{id:'no2',elementId:'outside2',x:650,y:400,width:190,height:110}],edges:[{id:'ei',relationshipId:'interrupt',sourceId:'inside',targetId:'outside',sourceNodeId:'ni',targetNodeId:'no',points:[],autoRouted:true}]};const types=['Block Definition Diagram','Internal Block Diagram','Requirement Diagram','Use Case Diagram','State Machine Diagram','Sequence Diagram','Parametric Diagram','Package Diagram','Instance Diagram'];p.diagrams=[activityDiagram,...types.map((diagramType,index)=>({id:`other-${index}`,name:`${diagramType} Example`,diagramType,ownerId:root,contextId:root,headerText:'',nodes:[],edges:[]}))];p.activeDiagramId='diagram';SystemsModelerAPI.setProject(p)})}

test('Activity palette exposes the full relationship set and a first-class endpoint editor',async({page})=>{await open(page);for(const kind of ['ControlFlow','ObjectFlow','InterruptingEdge','Allocate'])await expect(page.locator(`[data-tool="${kind}"][data-record-kind="relationship"]`),kind).toBeVisible();await expect(page.locator('[data-semantic-kind="InterruptibleActivityRegion"] .shape')).toHaveAttribute('stroke-dasharray','8 5');await expect(page.locator('.interrupting-edge-glyph')).toHaveCount(1);await page.locator('path.edge[data-semantic-kind="InterruptingEdge"]').click({force:true});await expect(page.getByLabel('Activity source')).toBeVisible();await expect(page.getByLabel('Activity target')).toBeVisible();await expect(page.getByLabel('Activity weight')).toHaveValue('2');await page.getByLabel('Activity target').selectOption('no2');expect(await page.evaluate(()=>{const p=SystemsModelerAPI.getProject(),r=p.relationships.find(x=>x.id==='interrupt'),e=p.diagrams.find(x=>x.id==='diagram').edges.find(x=>x.relationshipId==='interrupt');return{target:r.targetId,targetNode:e.targetNodeId}})).toEqual({target:'outside2',targetNode:'no2'});});

test('clicking the rendered frame header edits the header for every diagram type',async({page})=>{await open(page);const count=await page.locator('#diagramSelect option').count();for(let i=0;i<count;i++){const value=await page.locator('#diagramSelect option').nth(i).getAttribute('value');await page.locator('#diagramSelect').selectOption(value);await page.locator('.diagram-frame-header').dispatchEvent('pointerdown',{bubbles:true});const editor=page.getByLabel('Diagram header text');await expect(editor,`header editor for ${value}`).toBeVisible();await editor.fill(`custom header ${i}`);await editor.press('Enter');await expect(page.locator('.diagram-frame-title')).toHaveText(`custom header ${i}`);expect(await page.evaluate(id=>SystemsModelerAPI.getProject().diagrams.find(d=>d.id===id).headerText,value)).toBe(`custom header ${i}`);}});

test('clicking the workspace diagram title directly renames the active diagram',async({page})=>{await open(page);await page.locator('#diagramTitle').dispatchEvent('pointerdown',{bubbles:true});const editor=page.getByLabel('Diagram name');await expect(editor).toBeVisible();await editor.fill('Renamed Activity Diagram');await editor.press('Enter');await expect(page.locator('#diagramTitle')).toHaveText('Renamed Activity Diagram');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().diagrams[0].name)).toBe('Renamed Activity Diagram');});

test('clearing direct frame header text restores generated header behavior',async({page})=>{await open(page);await page.locator('.diagram-frame-header').dispatchEvent('pointerdown',{bubbles:true});const editor=page.getByLabel('Diagram header text');await editor.fill('');await editor.press('Enter');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().diagrams[0].headerText)).toBe('');await expect(page.locator('.diagram-frame-title')).toContainText('act');});
