import {test,expect} from './fixtures.mjs';

async function open(page){await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Activity UI'),root=p.root.id;const elements=[
{id:'activity',externalId:'ACT',kind:'Activity',metaclass:'Activity',name:'Process',ownerId:root},
{id:'region',externalId:'REG',kind:'InterruptibleActivityRegion',metaclass:'InterruptibleActivityRegion',name:'Abortable',ownerId:'activity',memberIds:['inside']},
{id:'inside',externalId:'IN',kind:'Action',metaclass:'Action',name:'Inside',ownerId:'region'},
{id:'outside',externalId:'OUT',kind:'Action',metaclass:'Action',name:'Outside',ownerId:'activity'}];p.elements.push(...elements);p.relationships.push({id:'interrupt',externalId:'INT',name:'abort',kind:'InterruptingEdge',metaclass:'ActivityEdge',stereotype:'',sourceId:'inside',targetId:'outside',ownerId:'activity',guard:'abortRequested',weight:'2',direction:'sourceToTarget',documentation:'',createdAt:new Date().toISOString(),modifiedAt:new Date().toISOString()});p.diagrams=[{id:'diagram',name:'Process Activity',diagramType:'Activity Diagram',ownerId:root,contextId:'activity',headerText:'',nodes:[{id:'nr',elementId:'region',x:120,y:120,width:360,height:250},{id:'ni',elementId:'inside',x:190,y:210,width:190,height:110,parentPresentationId:'nr'},{id:'no',elementId:'outside',x:650,y:210,width:190,height:110}],edges:[{id:'ei',relationshipId:'interrupt',sourceId:'inside',targetId:'outside',sourceNodeId:'ni',targetNodeId:'no',points:[],autoRouted:true}]}];p.activeDiagramId='diagram';SystemsModelerAPI.setProject(p)})}

test('Activity palette exposes all qualified relationships and interrupting notation',async({page})=>{await open(page);for(const kind of ['ControlFlow','ObjectFlow','InterruptingEdge','Allocate'])await expect(page.locator(`[data-tool="${kind}"][data-record-kind="relationship"]`),kind).toBeVisible();await expect(page.locator('[data-semantic-kind="InterruptibleActivityRegion"] .shape')).toHaveAttribute('stroke-dasharray','8 5');await expect(page.locator('.interrupting-edge-glyph')).toHaveCount(1);await page.locator('path.edge[data-semantic-kind="InterruptingEdge"]').click({force:true});await expect(page.getByRole('region',{name:'Properties'}).getByLabel('Weight')).toHaveValue('2');});

test('clicking the diagram frame header opens direct inline editing and persists custom text',async({page})=>{await open(page);await page.locator('.diagram-frame-header').click({force:true});const editor=page.getByLabel('Diagram header text');await expect(editor).toBeVisible();await editor.fill('act [Activity UI::Process] Operational Flow');await editor.press('Enter');await expect(page.locator('.diagram-frame-title')).toHaveText('act [Activity UI::Process] Operational Flow');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().diagrams[0].headerText)).toBe('act [Activity UI::Process] Operational Flow');});

test('clearing direct header text restores generated header behavior',async({page})=>{await open(page);await page.locator('.diagram-frame-header').click({force:true});const editor=page.getByLabel('Diagram header text');await editor.fill('');await editor.press('Enter');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().diagrams[0].headerText)).toBe('');await expect(page.locator('.diagram-frame-title')).toContainText('act');});
