import {test,expect} from './fixtures.mjs';

const advertised=['Action','CallBehaviorAction','CallOperationAction','SendSignalAction','AcceptEventAction','InputPin','OutputPin','ActivityParameterNode','ObjectNode','CentralBufferNode','DataStoreNode','InitialNode','ActivityFinalNode','FlowFinalNode','DecisionNode','MergeNode','ForkNode','JoinNode','ActivityPartition','Comment','ControlFlow','ObjectFlow','Allocate'];
async function open(page){await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Activity qualification'),root=p.root.id,records=[
  {id:'activity-context',externalId:'ACT-CONTEXT',kind:'Activity',metaclass:'Activity',name:'Process',ownerId:root},
  {id:'called-activity',externalId:'ACT-CALLED',kind:'Activity',metaclass:'Activity',name:'Called Process',ownerId:root},
  {id:'classifier-a',externalId:'TYPE-A',kind:'DataType',metaclass:'DataType',name:'Payload',ownerId:root},
  {id:'classifier-b',externalId:'TYPE-B',kind:'DataType',metaclass:'DataType',name:'Incompatible Payload',ownerId:root},
  {id:'operation-owner',externalId:'BLOCK-OPS',kind:'Block',metaclass:'Class',name:'Service',ownerId:root},
  {id:'operation',externalId:'OP-1',kind:'Operation',metaclass:'Operation',name:'perform',ownerId:'operation-owner'},
  {id:'signal',externalId:'SIG-1',kind:'Signal',metaclass:'Signal',name:'Start Signal',ownerId:root},
  {id:'event',externalId:'EVENT-1',kind:'Event',metaclass:'Event',name:'Start Event',ownerId:root},
  {id:'parameter',externalId:'PARAM-1',kind:'Parameter',metaclass:'Parameter',name:'payload',ownerId:'activity-context',typeRef:'classifier-a',direction:'in'}
];p.elements.push(...records);p.diagrams=[{id:'activity-diagram',name:'Process Activity',diagramType:'Activity Diagram',ownerId:root,contextId:'activity-context',nodes:[],edges:[]}];p.activeDiagramId='activity-diagram';SystemsModelerAPI.setProject(p)})}
const canvasClick=(page,x,y)=>page.locator('#canvas').click({position:{x,y}});
async function choose(dialog,id){await dialog.locator('select').selectOption(id);await dialog.getByRole('button',{name:'Use selected record'}).click()}
async function place(page,kind,x,y,referenceId=''){await page.locator(`[data-tool="${kind}"][data-record-kind="element"]`).click();await canvasClick(page,x,y);if(referenceId)await choose(page.locator('dialog:visible'),referenceId)}
async function connect(page,kind,source,target){await page.locator(`[data-tool="${kind}"][data-record-kind="relationship"]`).click();await source.click({force:true});await target.click({force:true})}

test('Activity production palette creates every advertised semantic and presentation workflow',async({page})=>{test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await open(page);
  for(const kind of advertised)await expect(page.locator(`[data-tool="${kind}"]`),kind).toBeVisible();
  await place(page,'InitialNode',70,150);await place(page,'Action',210,140);await place(page,'DecisionNode',430,150);await place(page,'MergeNode',570,150);await place(page,'ForkNode',710,150);await place(page,'JoinNode',850,150);await place(page,'ActivityFinalNode',1000,150);await place(page,'FlowFinalNode',1100,150);
  await place(page,'CallBehaviorAction',180,350,'called-activity');await place(page,'CallOperationAction',390,350,'operation');await place(page,'SendSignalAction',600,350,'signal');await place(page,'AcceptEventAction',810,350,'event');
  await place(page,'ObjectNode',180,560,'classifier-a');await place(page,'CentralBufferNode',400,560,'classifier-a');await place(page,'DataStoreNode',620,560,'classifier-a');await place(page,'ActivityParameterNode',840,560,'parameter');await place(page,'ActivityPartition',1080,430);await place(page,'Comment',1080,650);
  for(const kind of advertised.filter(kind=>!['InputPin','OutputPin','ControlFlow','ObjectFlow','Allocate'].includes(kind)))await expect(page.locator(`[data-semantic-kind="${kind}"]`),kind).toHaveCount(1);
  const action=page.locator('[data-semantic-kind="Action"]');await action.click();await page.locator('#properties').getByLabel('Name',{exact:true}).fill('Transform');await page.locator('#properties').getByLabel('Documentation').fill('Transforms the payload continuously.');await page.locator('#properties').getByLabel('Documentation').blur();
  await page.locator('[data-tool="OutputPin"]').click();await action.click();await choose(page.locator('dialog:visible'),'classifier-a');await page.locator('[data-tool="InputPin"]').click();await action.click();await choose(page.locator('dialog:visible'),'classifier-a');await page.locator('[data-tool="InputPin"]').click();await action.click();await choose(page.locator('dialog:visible'),'classifier-b');
  const output=page.locator('[data-semantic-kind="OutputPin"]'),inputs=page.locator('[data-semantic-kind="InputPin"]');await expect(output).toHaveCount(1);await expect(inputs).toHaveCount(2);
  await connect(page,'ObjectFlow',output,inputs.first());const validCount=await page.evaluate(()=>SystemsModelerAPI.getProject().relationships.length);await connect(page,'ObjectFlow',output,inputs.nth(1));expect(await page.evaluate(()=>SystemsModelerAPI.getProject().relationships.length)).toBe(validCount);await expect(page.locator('#log')).toContainText('no common compatible classifier');
  await connect(page,'ControlFlow',page.locator('[data-semantic-kind="InitialNode"]'),action);await connect(page,'ControlFlow',action,page.locator('[data-semantic-kind="DecisionNode"]'));
  await connect(page,'Allocate',action,page.locator('[data-semantic-kind="ObjectNode"]'));await expect(page.locator('.edge-label')).toContainText('«allocate»');
  await page.locator('[data-semantic-kind="ForkNode"]').click();await page.locator('#properties').getByLabel('Orientation').selectOption('vertical');await expect(page.locator('[data-semantic-kind="ForkNode"] rect')).toHaveAttribute('width','8');
  const before=await page.evaluate(()=>{const p=SystemsModelerAPI.getProject();return{elements:p.elements.map(e=>({id:e.id,kind:e.kind,ownerId:e.ownerId,typeRef:e.typeRef,parameterId:e.parameterId,referencedBehaviorId:e.referencedBehaviorId,referencedOperationId:e.referencedOperationId,signalId:e.signalId,eventId:e.eventId})),nodes:p.diagrams[0].nodes.map(n=>({id:n.id,elementId:n.elementId})),relationships:p.relationships.map(r=>({id:r.id,kind:r.kind,sourceId:r.sourceId,targetId:r.targetId,guard:r.guard}))}});await page.locator('#saveProject').click();await page.reload();await page.waitForFunction(()=>window.SystemsModelerAPI);const after=await page.evaluate(()=>{const p=SystemsModelerAPI.getProject();return{elements:p.elements.map(e=>({id:e.id,kind:e.kind,ownerId:e.ownerId,typeRef:e.typeRef,parameterId:e.parameterId,referencedBehaviorId:e.referencedBehaviorId,referencedOperationId:e.referencedOperationId,signalId:e.signalId,eventId:e.eventId})),nodes:p.diagrams[0].nodes.map(n=>({id:n.id,elementId:n.elementId})),relationships:p.relationships.map(r=>({id:r.id,kind:r.kind,sourceId:r.sourceId,targetId:r.targetId,guard:r.guard}))}});expect(after).toEqual(before);expect(after.relationships.every(r=>!after.nodes.some(n=>n.id===r.sourceId||n.id===r.targetId))).toBe(true);expect(errors).toEqual([])
});

test('presentation deletion and containment reuse preserve Activity semantics',async({page})=>{await open(page);await place(page,'Action',200,180);const ids=await page.locator('[data-semantic-kind="Action"]').evaluate(node=>({semantic:node.dataset.semanticId,presentation:node.dataset.presentationId}));await page.locator('[data-semantic-kind="Action"]').click();await page.locator('#deleteSelected').click();expect(await page.evaluate(id=>SystemsModelerAPI.getProject().elements.some(e=>e.id===id),ids.semantic)).toBe(true);await page.evaluate(({semantic,presentation})=>{const p=SystemsModelerAPI.getProject(),d=p.diagrams[0];d.nodes.push({id:`${presentation}-reused`,elementId:semantic,x:420,y:180,width:190,height:110});SystemsModelerAPI.setProject(p)},{...ids});await expect(page.locator('[data-semantic-kind="Action"]')).toHaveAttribute('data-semantic-id',ids.semantic);await expect(page.locator('[data-semantic-kind="Action"]')).not.toHaveAttribute('data-presentation-id',ids.presentation)});
