import {test,expect} from './fixtures.mjs';

const TYPES=['Block Definition Diagram','Internal Block Diagram','Requirement Diagram','Use Case Diagram','Activity Diagram','State Machine Diagram','Sequence Diagram','Parametric Diagram','Package Diagram'];

for(const [index,type] of TYPES.entries())test(`inline diagram header editing works for ${type}`,async({page})=>{await page.goto('/');await page.evaluate(({type,index})=>{const p=SystemsModelerAPI.createBlankProject('Header Test'),root=p.root.id;p.diagrams=[{id:`d${index}`,name:'New Diagram',diagramType:type,ownerId:root,contextId:root,headerText:'',nodes:[],edges:[]}];p.activeDiagramId=`d${index}`;SystemsModelerAPI.setProject(p)},{type,index});const hit=page.locator('.diagram-header-hit-surface');await expect(hit).toBeVisible();await hit.click({force:true});const input=page.getByLabel('Diagram header text');await expect(input).toBeVisible();await expect(input).toBeFocused();await input.fill(`${type} custom header`);await input.press('Enter');await expect(page.locator('.diagram-frame-title')).toHaveText(`${type} custom header`);expect(await page.evaluate(()=>SystemsModelerAPI.getProject().diagrams[0].headerText)).toBe(`${type} custom header`);});

test('clearing header restores generated header',async({page})=>{await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Header Test'),root=p.root.id;p.diagrams=[{id:'d',name:'New Diagram',diagramType:'Activity Diagram',ownerId:root,contextId:root,headerText:'custom',nodes:[],edges:[]}];p.activeDiagramId='d';SystemsModelerAPI.setProject(p)});await page.locator('.diagram-header-hit-surface').click({force:true});const input=page.getByLabel('Diagram header text');await input.fill('');await input.press('Enter');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().diagrams[0].headerText)).toBe('');await expect(page.locator('.diagram-frame-title')).toContainText('act [');});

test('diagram header width and height can be resized and persist',async({page})=>{await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Header Resize'),root=p.root.id;p.diagrams=[{id:'d',name:'Resizable',diagramType:'Block Definition Diagram',ownerId:root,contextId:root,headerText:'',nodes:[],edges:[]}];p.activeDiagramId='d';SystemsModelerAPI.setProject(p)});const handle=page.getByRole('separator',{name:'Resize diagram header'});await expect(handle).toBeVisible();const box=await handle.boundingBox();expect(box).toBeTruthy();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+170,box.y+45,{steps:5});await page.mouse.up();const stored=await page.evaluate(()=>{const d=SystemsModelerAPI.getProject().diagrams[0];return{width:d.headerWidth,height:d.headerHeight}});expect(stored.width).toBeGreaterThan(534);expect(stored.height).toBeGreaterThan(34);await expect(page.locator('.diagram-frame-header')).toHaveAttribute('data-header-width',String(stored.width));await expect(page.locator('.diagram-frame-header')).toHaveAttribute('data-header-height',String(stored.height));});
