import {test,expect} from './fixtures.mjs';
import * as XLSX from 'xlsx';

function workbookBuffer(sheets){const wb=XLSX.utils.book_new();for(const [name,rows] of Object.entries(sheets))XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),name);return XLSX.write(wb,{type:'buffer',bookType:'xlsx'})}

async function open(page){await page.goto('/');await page.evaluate(()=>{localStorage.clear();const p=SystemsModelerAPI.createBlankProject('Import Browser Test');SystemsModelerAPI.setProject(p)})}

test('valid CATIA workbook import commits transactionally into the active project',async({page})=>{await open(page);const initialProjectId=await page.evaluate(()=>SystemsModelerAPI.getProject().id);const buffer=workbookBuffer({Packages_Import:[{'External ID':'PKG-1','Name':'Architecture'}],Blocks_Import:[{'External ID':'BLK-1','Name':'System','Owner External ID':'PKG-1'}],Requirements_Import:[{'External ID':'REQ-1','Name':'Shall operate','Owner External ID':'PKG-1','Requirement ID':'REQ-1','Requirement Text':'The system shall operate.'}]});await page.locator('#workbookInput').setInputFiles({name:'valid.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await expect.poll(()=>page.evaluate(()=>SystemsModelerAPI.getProject().elements.some(e=>e.id==='BLK-1'))).toBe(true);const state=await page.evaluate(()=>({projectId:SystemsModelerAPI.getProject().id,block:SystemsModelerAPI.getProject().elements.find(e=>e.id==='BLK-1'),req:SystemsModelerAPI.getProject().elements.find(e=>e.id==='REQ-1'),savedProjectIds:SystemsModelerProjects.list().map(p=>p.id)}));expect(state.projectId).toBe(initialProjectId);expect(state.block.ownerId).toBe('PKG-1');expect(state.req.requirementText).toBe('The system shall operate.');expect(state.savedProjectIds).toContain(initialProjectId);});

test('unresolved owner import is rejected and leaves the active project unchanged',async({page})=>{await open(page);const before=await page.evaluate(()=>JSON.stringify(SystemsModelerAPI.getProject()));const buffer=workbookBuffer({Blocks_Import:[{'External ID':'BAD-1','Name':'Bad Block','Owner External ID':'MISSING_OWNER'}]});await page.locator('#workbookInput').setInputFiles({name:'bad-owner.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await expect.poll(()=>page.evaluate(()=>document.getElementById('log').textContent.includes('Import rejected'))).toBe(true);expect(await page.evaluate(()=>JSON.stringify(SystemsModelerAPI.getProject()))).toBe(before);});

test('stable ID kind mutation on reimport is rejected',async({page})=>{await open(page);await page.evaluate(()=>{const p=SystemsModelerAPI.getProject(),e={id:'STABLE-1',externalId:'STABLE-1',kind:'Block',metaclass:'Class',stereotype:'Block',name:'Original',ownerId:p.root.id,documentation:'',compartments:{},compartmentVisibility:{}};p.elements.push(e);SystemsModelerAPI.setProject(p)});const buffer=workbookBuffer({InterfaceBlocks_Import:[{'External ID':'STABLE-1','Name':'Changed','Owner External ID':''}]});await page.locator('#workbookInput').setInputFiles({name:'kind-change.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await expect.poll(()=>page.evaluate(()=>document.getElementById('log').textContent.includes('Import rejected'))).toBe(true);expect(await page.evaluate(()=>SystemsModelerAPI.getProject().elements.find(e=>e.id==='STABLE-1').kind)).toBe('Block');});
