import {test,expect} from './fixtures.mjs';

async function clearProjects(page){await page.goto('/');await page.evaluate(()=>{localStorage.removeItem('systems-modeler.projects.v2');localStorage.removeItem('systems-modeler.projects.v1');localStorage.removeItem('systems-modeler.activeProject.v1');localStorage.removeItem('systems-modeler.v6.2')});await page.reload();await page.waitForFunction(()=>Boolean(window.SystemsModelerProjects&&window.SystemsModelerAPI));}

test('toolbar New preserves the outgoing project and autosave cannot overwrite it',async({page})=>{await clearProjects(page);await page.evaluate(()=>{const p=SystemsModelerAPI.getProject();p.name='Project A';p.elements.push({id:'a-marker',externalId:'A-MARKER',kind:'Comment',metaclass:'Comment',name:'A survives',ownerId:p.root.id,documentation:'Project A data'});SystemsModelerProjects.saveCurrent('test-a')});const aId=await page.evaluate(()=>SystemsModelerAPI.getProject().id);page.once('dialog',dialog=>dialog.accept());page.once('dialog',dialog=>dialog.accept('Project B'));await page.locator('#newProject').click();await page.waitForTimeout(3500);const state=await page.evaluate(aId=>({active:SystemsModelerProjects.activeId(),current:SystemsModelerAPI.getProject(),saved:SystemsModelerProjects.list().find(x=>x.id===aId)}),aId);expect(state.active).not.toBe(aId);expect(state.current.name).toBe('Project B');expect(state.saved.project.name).toBe('Project A');expect(state.saved.project.elements.some(e=>e.id==='a-marker'&&e.documentation==='Project A data')).toBe(true)});

test('multiple projects switch independently without losing model data',async({page})=>{await clearProjects(page);const ids=await page.evaluate(()=>{let a=SystemsModelerAPI.getProject();a.name='Alpha';a.elements.push({id:'alpha-only',externalId:'ALPHA',kind:'Comment',metaclass:'Comment',name:'Alpha only',ownerId:a.root.id});SystemsModelerProjects.saveCurrent('alpha');const alpha=a.id;SystemsModelerProjects.createNewProject('Beta');let b=SystemsModelerAPI.getProject();b.elements.push({id:'beta-only',externalId:'BETA',kind:'Comment',metaclass:'Comment',name:'Beta only',ownerId:b.root.id});SystemsModelerProjects.saveCurrent('beta');return{alpha,beta:b.id}});await page.evaluate(id=>SystemsModelerProjects.openProject(id),ids.alpha);await expect.poll(()=>page.evaluate(()=>SystemsModelerAPI.getProject().name)).toBe('Alpha');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().elements.some(e=>e.id==='alpha-only'))).toBe(true);expect(await page.evaluate(()=>SystemsModelerAPI.getProject().elements.some(e=>e.id==='beta-only'))).toBe(false);await page.evaluate(id=>SystemsModelerProjects.openProject(id),ids.beta);await expect.poll(()=>page.evaluate(()=>SystemsModelerAPI.getProject().name)).toBe('Beta');expect(await page.evaluate(()=>SystemsModelerAPI.getProject().elements.some(e=>e.id==='beta-only'))).toBe(true)});

test('opening external JSON with an existing project id forks identity instead of replacing saved project',async({page})=>{await clearProjects(page);const original=await page.evaluate(()=>{const p=SystemsModelerAPI.getProject();p.name='Original';p.elements.push({id:'original-marker',externalId:'ORIG',kind:'Comment',metaclass:'Comment',name:'Original marker',ownerId:p.root.id});SystemsModelerProjects.saveCurrent('original');return{id:p.id,copy:structuredClone(p)}});await page.evaluate(async original=>{const imported=structuredClone(original.copy);imported.name='Imported Collision';imported.elements=imported.elements.filter(e=>e.id!=='original-marker');await SystemsModelerProjects.openExternalProject(imported,{fileName:'collision.sysml.json'})},original);const result=await page.evaluate(originalId=>({current:SystemsModelerAPI.getProject(),items:SystemsModelerProjects.list(),original:SystemsModelerProjects.list().find(x=>x.id===originalId)}),original.id);expect(result.current.id).not.toBe(original.id);expect(result.current.name).toBe('Imported Collision');expect(result.original.project.name).toBe('Original');expect(result.original.project.elements.some(e=>e.id==='original-marker')).toBe(true);expect(result.items.length).toBeGreaterThanOrEqual(2)});

test('autosave creates recovery history before replacing a changed snapshot',async({page})=>{await clearProjects(page);await page.evaluate(()=>{const p=SystemsModelerAPI.getProject();p.name='Recovery Test';SystemsModelerProjects.saveCurrent('baseline');p.documentation='changed once';SystemsModelerProjects.saveCurrent('changed')});const item=await page.evaluate(()=>SystemsModelerProjects.list().find(x=>x.id===SystemsModelerProjects.activeId()));expect(item.history.length).toBeGreaterThan(0);expect(item.history.at(-1).project.documentation||'').toBe('')});
