import {test,expect} from './fixtures.mjs';

async function compositionFixture(page){await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Standards Browser'),root=p.root.id;const whole={id:'whole',externalId:'WHOLE',kind:'Block',metaclass:'Class',stereotype:'block',name:'Whole',ownerId:root,documentation:'',compartments:{},compartmentVisibility:{}},part={id:'part',externalId:'PART',kind:'Block',metaclass:'Class',stereotype:'block',name:'Part',ownerId:root,documentation:'',compartments:{},compartmentVisibility:{}};p.elements=[whole,part];p.relationships=[{id:'comp',externalId:'COMP',kind:'Composition',metaclass:'Association',stereotype:'',name:'',sourceId:'part',targetId:'whole',ownerId:root,sourceRole:'child',targetRole:'owner',sourceMultiplicity:'1',targetMultiplicity:'1',sourceNavigable:true,targetNavigable:true,sourceAggregation:'none',targetAggregation:'composite',sourceEndOwned:false,targetEndOwned:true,sourceEndId:'child-end',targetEndId:'owner-end',documentation:''}];p.diagrams=[{id:'d',name:'BDD',diagramType:'Block Definition Diagram',ownerId:root,contextId:root,nodes:[{id:'part-node',elementId:'part',x:100,y:120,width:190,height:110},{id:'whole-node',elementId:'whole',x:500,y:120,width:190,height:110}],edges:[{id:'e',relationshipId:'comp',sourceId:'part',targetId:'whole',sourceNodeId:'part-node',targetNodeId:'whole-node',points:[]}]}];p.activeDiagramId='d';SystemsModelerAPI.setProject(p)});await page.waitForFunction(()=>Boolean(window.SystemsModelerStandardsUI));await page.evaluate(()=>SystemsModelerStandardsUI.synchronize())}

test('legacy child-to-owner Composition is canonicalized to owner/source and renders source diamond',async({page})=>{await compositionFixture(page);const edge=page.locator('path.edge[data-semantic-id="comp"]');await expect(edge).toBeVisible();await expect.poll(()=>edge.getAttribute('marker-start')).toContain('diamondFilled');expect(await edge.getAttribute('marker-end')).toBeNull();const state=await page.evaluate(()=>{const p=SystemsModelerAPI.getProject(),r=p.relationships.find(x=>x.id==='comp'),e=p.diagrams[0].edges.find(x=>x.id==='e');return{r,e}});expect(state.r.sourceId).toBe('whole');expect(state.r.targetId).toBe('part');expect(state.r.sourceAggregation).toBe('composite');expect(state.r.targetAggregation).toBe('none');expect(state.r.ownerEnd).toBe('source');expect(state.e.sourceNodeId).toBe('whole-node');expect(state.e.targetNodeId).toBe('part-node')});

test('selected Composition reports owner/source and can swap semantic owner while keeping diamond on source',async({page})=>{await compositionFixture(page);await page.locator('path.edge[data-semantic-id="comp"]').click();const editor=page.locator('.uml-aggregate-end-editor');await expect(editor).toContainText('Owner/source: Whole');await editor.getByRole('button',{name:'Swap owner and child'}).click();await expect.poll(()=>page.locator('path.edge[data-semantic-id="comp"]').getAttribute('marker-start')).toContain('diamondFilled');expect(await page.locator('path.edge[data-semantic-id="comp"]').getAttribute('marker-end')).toBeNull();const rel=await page.evaluate(()=>SystemsModelerAPI.getProject().relationships.find(r=>r.id==='comp'));expect(rel.sourceId).toBe('part');expect(rel.targetId).toBe('whole');expect(rel.sourceAggregation).toBe('composite');expect(rel.ownerEnd).toBe('source')});

test('legacy target-marker overlay is suppressed when standards rendering owns relationship ends',async({page})=>{await compositionFixture(page);const overlays=page.locator('line.marker-overlay');if(await overlays.count())await expect(overlays.first()).toHaveCSS('display','none')});
