import {test,expect} from './fixtures.mjs';

async function compositionFixture(page){await page.goto('/');await page.evaluate(()=>{const p=SystemsModelerAPI.createBlankProject('Standards Browser'),root=p.root.id;const whole={id:'whole',externalId:'WHOLE',kind:'Block',metaclass:'Class',stereotype:'block',name:'Whole',ownerId:root,documentation:'',compartments:{},compartmentVisibility:{}},part={id:'part',externalId:'PART',kind:'Block',metaclass:'Class',stereotype:'block',name:'Part',ownerId:root,documentation:'',compartments:{},compartmentVisibility:{}};p.elements=[whole,part];p.relationships=[{id:'comp',externalId:'COMP',kind:'Composition',metaclass:'Association',stereotype:'',name:'',sourceId:'part',targetId:'whole',ownerId:root,sourceRole:'',targetRole:'',sourceMultiplicity:'1',targetMultiplicity:'1',sourceNavigable:true,targetNavigable:true,sourceAggregation:'composite',targetAggregation:'none',sourceEndOwned:false,targetEndOwned:true,sourceEndId:'se',targetEndId:'te',documentation:''}];p.diagrams=[{id:'d',name:'BDD',diagramType:'Block Definition Diagram',ownerId:root,contextId:root,nodes:[{id:'n1',elementId:'part',x:100,y:120,width:190,height:110},{id:'n2',elementId:'whole',x:500,y:120,width:190,height:110}],edges:[{id:'e',relationshipId:'comp',sourceId:'part',targetId:'whole',sourceNodeId:'n1',targetNodeId:'n2',points:[]}]}];p.activeDiagramId='d';SystemsModelerAPI.setProject(p)});await page.waitForFunction(()=>Boolean(window.SystemsModelerStandardsUI));await page.evaluate(()=>SystemsModelerStandardsUI.synchronize())}

test('Composition renders the filled diamond at the whole/owner target end',async({page})=>{await compositionFixture(page);const edge=page.locator('path.edge[data-semantic-id="comp"]');await expect(edge).toBeVisible();await expect.poll(()=>edge.getAttribute('marker-end')).toContain('diamondFilled');expect(await edge.getAttribute('marker-start')).toBeNull();const rel=await page.evaluate(()=>SystemsModelerAPI.getProject().relationships.find(r=>r.id==='comp'));expect(rel.sourceAggregation).toBe('none');expect(rel.targetAggregation).toBe('composite');expect(rel.aggregateEnd).toBe('target')});

test('selected Composition exposes editable whole-end control',async({page})=>{await compositionFixture(page);await page.locator('path.edge[data-semantic-id="comp"]').click();const editor=page.locator('.uml-aggregate-end-editor select');await expect(editor).toBeVisible();await expect(editor).toHaveValue('target');await editor.selectOption('source');await expect.poll(()=>page.locator('path.edge[data-semantic-id="comp"]').getAttribute('marker-start')).toContain('diamondFilled');const rel=await page.evaluate(()=>SystemsModelerAPI.getProject().relationships.find(r=>r.id==='comp'));expect(rel.aggregateEnd).toBe('source');expect(rel.aggregateEndExplicit).toBe(true)});

test('legacy target-marker overlay is suppressed when standards rendering owns relationship ends',async({page})=>{await compositionFixture(page);const overlays=page.locator('line.marker-overlay');if(await overlays.count())await expect(overlays.first()).toHaveCSS('display','none')});
