import {app,BrowserWindow,dialog,ipcMain,Menu,protocol,shell} from 'electron';
import {readFile} from 'node:fs/promises';import {extname,join,normalize,relative} from 'node:path';import {fileURLToPath} from 'node:url';
import {atomicWrite} from './file-service.mjs';import {IPC,IMPORT_FILTERS,MENU_COMMANDS,PROJECT_FILTERS,validateSuggestedName,validateText} from './ipc-contract.mjs';
const root=join(fileURLToPath(new URL('..',import.meta.url)),'public');let win,currentPath=null,dirty=false;const devUrl=process.env.MODELER_DESKTOP_DEV_URL;
protocol.registerSchemesAsPrivileged([{scheme:'modeler',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true}}]);
function send(command){if(MENU_COMMANDS.has(command))win?.webContents.send('menu:command',command)}
function menu(){const development=!app.isPackaged;return Menu.buildFromTemplate([{label:'File',submenu:[{label:'New Project',accelerator:'CmdOrCtrl+N',click:()=>send('new')},{label:'Open Project…',accelerator:'CmdOrCtrl+O',click:()=>send('open')},{label:'Save',accelerator:'CmdOrCtrl+S',click:()=>send('save')},{label:'Save As…',accelerator:'CmdOrCtrl+Shift+S',click:()=>send('save-as')},{type:'separator'},{label:'Import…',click:()=>send('import')},{label:'Export…',click:()=>send('export')},{type:'separator'},{role:'quit'}]},{label:'Edit',submenu:[{role:'undo'},{role:'redo'},{type:'separator'},{role:'cut'},{role:'copy'},{role:'paste'},{role:'selectAll'}]},{label:'View',submenu:[{role:'reload'},...(development?[{role:'toggleDevTools'}]:[])]},{role:'help',submenu:[{label:'About Systems Modeler',click:()=>dialog.showMessageBox(win,{type:'info',title:'About Systems Modeler',message:`Systems Modeler ${app.getVersion()}`,detail:'Secure Electron desktop development foundation'})}]}])}
async function confirmDiscard(){if(!dirty)return true;return(await dialog.showMessageBox(win,{type:'warning',buttons:['Cancel','Discard Changes'],defaultId:0,cancelId:0,message:'This project has unsaved changes.',detail:'Discard them and continue?'})).response===1}
async function createWindow(){win=new BrowserWindow({width:1440,height:940,minWidth:1100,minHeight:700,show:false,webPreferences:{preload:join(fileURLToPath(new URL('.',import.meta.url)),'preload.mjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.webContents.setWindowOpenHandler(({url})=>{if(/^https:\/\//.test(url))void shell.openExternal(url);return{action:'deny'}});win.webContents.on('will-navigate',(event,url)=>{const allowed=devUrl?new URL(url).origin===new URL(devUrl).origin:url.startsWith('modeler://app/');if(!allowed)event.preventDefault()});win.on('close',event=>{if(dirty&&!win.__confirmedClose){event.preventDefault();void confirmDiscard().then(ok=>{if(ok){win.__confirmedClose=true;win.close()}})}});await win.loadURL(devUrl||'modeler://app/index.html');win.show()}
function registerIpc(){ipcMain.handle(IPC.metadata,()=>({name:app.getName(),version:app.getVersion(),packaged:app.isPackaged}));ipcMain.on(IPC.setDirty,(_e,value)=>{dirty=value===true;win?.setDocumentEdited(dirty)});ipcMain.handle(IPC.openProject,async()=>{if(!await confirmDiscard())return null;const result=await dialog.showOpenDialog(win,{properties:['openFile'],filters:PROJECT_FILTERS});if(result.canceled)return null;const path=result.filePaths[0],content=await readFile(path,'utf8');validateText(content);currentPath=path;dirty=false;return{path,name:path.split(/[\\/]/).at(-1),content}});ipcMain.handle(IPC.importFile,async()=>{const result=await dialog.showOpenDialog(win,{properties:['openFile'],filters:IMPORT_FILTERS});if(result.canceled)return null;const path=result.filePaths[0],data=await readFile(path);if(data.byteLength>50_000_000)throw new RangeError('Import exceeds the 50 MB desktop safety limit.');return{name:path.split(/[\\/]/).at(-1),extension:extname(path).toLowerCase(),bytes:[...data]}});const save=async(_e,arg,force,mime)=>{if(!arg||typeof arg!=='object')throw new TypeError('Save request is invalid.');const content=validateText(arg.content),suggestedName=validateSuggestedName(arg.suggestedName);let path=!force&&currentPath;if(!path){const result=await dialog.showSaveDialog(win,{defaultPath:suggestedName,filters:mime?[{name:'Export',extensions:[suggestedName.split('.').at(-1)]}]:PROJECT_FILTERS});if(result.canceled)return null;path=result.filePath}await atomicWrite(path,content);if(!mime){currentPath=path;dirty=false;win?.setDocumentEdited(false)}return{path,name:path.split(/[\\/]/).at(-1)}};ipcMain.handle(IPC.saveProject,(e,arg)=>save(e,arg,false));ipcMain.handle(IPC.saveProjectAs,(e,arg)=>save(e,arg,true));ipcMain.handle(IPC.exportFile,(e,arg)=>save(e,arg,true,arg?.mime||'application/octet-stream'))}
app.whenReady().then(async()=>{if(!devUrl)protocol.handle('modeler',async request=>{const url=new URL(request.url),requested=decodeURIComponent(url.pathname).replace(/^\/+/, '')||'index.html',candidate=normalize(join(root,requested)),outside=relative(root,candidate).startsWith('..');if(outside)return new Response('Forbidden',{status:403});try{return new Response(await readFile(candidate),{headers:{'content-type':extname(candidate)==='.js'?'text/javascript':extname(candidate)==='.css'?'text/css':'text/html'}})}catch{return new Response('Renderer asset not found. Run npm run desktop:build.',{status:404})}});registerIpc();Menu.setApplicationMenu(menu());await createWindow()});app.on('window-all-closed',()=>app.quit());
